// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/accountType/accountType.proto

package accountType

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	SerialNumber  int32                  `protobuf:"varint,2,opt,name=SerialNumber,proto3" json:"SerialNumber,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=Title,proto3" json:"Title,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,5,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,7,opt,name=UpdatedBy,proto3" json:"UpdatedBy,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`
	DeletedBy     string                 `protobuf:"bytes,9,opt,name=DeletedBy,proto3" json:"DeletedBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountType) Reset() {
	*x = AccountType{}
	mi := &file_proto_accountType_accountType_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountType) ProtoMessage() {}

func (x *AccountType) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accountType_accountType_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountType.ProtoReflect.Descriptor instead.
func (*AccountType) Descriptor() ([]byte, []int) {
	return file_proto_accountType_accountType_proto_rawDescGZIP(), []int{0}
}

func (x *AccountType) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *AccountType) GetSerialNumber() int32 {
	if x != nil {
		return x.SerialNumber
	}
	return 0
}

func (x *AccountType) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *AccountType) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *AccountType) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *AccountType) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *AccountType) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *AccountType) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *AccountType) GetDeletedBy() string {
	if x != nil {
		return x.DeletedBy
	}
	return ""
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	SortBy        string                 `protobuf:"bytes,3,opt,name=SortBy,proto3" json:"SortBy,omitempty"`
	Order         string                 `protobuf:"bytes,4,opt,name=Order,proto3" json:"Order,omitempty"`
	SearchTerm    string                 `protobuf:"bytes,5,opt,name=SearchTerm,proto3" json:"SearchTerm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_proto_accountType_accountType_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accountType_accountType_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_proto_accountType_accountType_proto_rawDescGZIP(), []int{1}
}

func (x *Filter) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Filter) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Filter) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *Filter) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *Filter) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

type Stats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	TotalAmount   float32                `protobuf:"fixed32,2,opt,name=TotalAmount,proto3" json:"TotalAmount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_proto_accountType_accountType_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accountType_accountType_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_proto_accountType_accountType_proto_rawDescGZIP(), []int{2}
}

func (x *Stats) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Stats) GetTotalAmount() float32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type CreateAccountTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acct          *AccountType           `protobuf:"bytes,1,opt,name=Acct,proto3" json:"Acct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountTypeRequest) Reset() {
	*x = CreateAccountTypeRequest{}
	mi := &file_proto_accountType_accountType_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountTypeRequest) ProtoMessage() {}

func (x *CreateAccountTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accountType_accountType_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountTypeRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountTypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_accountType_accountType_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAccountTypeRequest) GetAcct() *AccountType {
	if x != nil {
		return x.Acct
	}
	return nil
}

type CreateAccountTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountTypeResponse) Reset() {
	*x = CreateAccountTypeResponse{}
	mi := &file_proto_accountType_accountType_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountTypeResponse) ProtoMessage() {}

func (x *CreateAccountTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accountType_accountType_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountTypeResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountTypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_accountType_accountType_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAccountTypeResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetAccountTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acct          *AccountType           `protobuf:"bytes,1,opt,name=Acct,proto3" json:"Acct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountTypeRequest) Reset() {
	*x = GetAccountTypeRequest{}
	mi := &file_proto_accountType_accountType_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountTypeRequest) ProtoMessage() {}

func (x *GetAccountTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accountType_accountType_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountTypeRequest.ProtoReflect.Descriptor instead.
func (*GetAccountTypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_accountType_accountType_proto_rawDescGZIP(), []int{5}
}

func (x *GetAccountTypeRequest) GetAcct() *AccountType {
	if x != nil {
		return x.Acct
	}
	return nil
}

type GetAccountTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acct          *AccountType           `protobuf:"bytes,1,opt,name=Acct,proto3" json:"Acct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountTypeResponse) Reset() {
	*x = GetAccountTypeResponse{}
	mi := &file_proto_accountType_accountType_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountTypeResponse) ProtoMessage() {}

func (x *GetAccountTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accountType_accountType_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountTypeResponse.ProtoReflect.Descriptor instead.
func (*GetAccountTypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_accountType_accountType_proto_rawDescGZIP(), []int{6}
}

func (x *GetAccountTypeResponse) GetAcct() *AccountType {
	if x != nil {
		return x.Acct
	}
	return nil
}

type UpdateAccountTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acct          *AccountType           `protobuf:"bytes,1,opt,name=Acct,proto3" json:"Acct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountTypeRequest) Reset() {
	*x = UpdateAccountTypeRequest{}
	mi := &file_proto_accountType_accountType_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountTypeRequest) ProtoMessage() {}

func (x *UpdateAccountTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accountType_accountType_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountTypeRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountTypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_accountType_accountType_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAccountTypeRequest) GetAcct() *AccountType {
	if x != nil {
		return x.Acct
	}
	return nil
}

type UpdateAccountTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acct          *AccountType           `protobuf:"bytes,1,opt,name=Acct,proto3" json:"Acct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountTypeResponse) Reset() {
	*x = UpdateAccountTypeResponse{}
	mi := &file_proto_accountType_accountType_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountTypeResponse) ProtoMessage() {}

func (x *UpdateAccountTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accountType_accountType_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountTypeResponse.ProtoReflect.Descriptor instead.
func (*UpdateAccountTypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_accountType_accountType_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAccountTypeResponse) GetAcct() *AccountType {
	if x != nil {
		return x.Acct
	}
	return nil
}

type DeleteAccountTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acct          *AccountType           `protobuf:"bytes,1,opt,name=Acct,proto3" json:"Acct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountTypeRequest) Reset() {
	*x = DeleteAccountTypeRequest{}
	mi := &file_proto_accountType_accountType_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountTypeRequest) ProtoMessage() {}

func (x *DeleteAccountTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accountType_accountType_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountTypeRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountTypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_accountType_accountType_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteAccountTypeRequest) GetAcct() *AccountType {
	if x != nil {
		return x.Acct
	}
	return nil
}

type DeleteAccountTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountTypeResponse) Reset() {
	*x = DeleteAccountTypeResponse{}
	mi := &file_proto_accountType_accountType_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountTypeResponse) ProtoMessage() {}

func (x *DeleteAccountTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accountType_accountType_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountTypeResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccountTypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_accountType_accountType_proto_rawDescGZIP(), []int{10}
}

type ListAccountTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=Filter,proto3" json:"Filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountTypeRequest) Reset() {
	*x = ListAccountTypeRequest{}
	mi := &file_proto_accountType_accountType_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountTypeRequest) ProtoMessage() {}

func (x *ListAccountTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accountType_accountType_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountTypeRequest.ProtoReflect.Descriptor instead.
func (*ListAccountTypeRequest) Descriptor() ([]byte, []int) {
	return file_proto_accountType_accountType_proto_rawDescGZIP(), []int{11}
}

func (x *ListAccountTypeRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListAccountTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acct          []*AccountType         `protobuf:"bytes,1,rep,name=Acct,proto3" json:"Acct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountTypeResponse) Reset() {
	*x = ListAccountTypeResponse{}
	mi := &file_proto_accountType_accountType_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountTypeResponse) ProtoMessage() {}

func (x *ListAccountTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accountType_accountType_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountTypeResponse.ProtoReflect.Descriptor instead.
func (*ListAccountTypeResponse) Descriptor() ([]byte, []int) {
	return file_proto_accountType_accountType_proto_rawDescGZIP(), []int{12}
}

func (x *ListAccountTypeResponse) GetAcct() []*AccountType {
	if x != nil {
		return x.Acct
	}
	return nil
}

type AccountTypeStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=Filter,proto3" json:"Filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountTypeStatsRequest) Reset() {
	*x = AccountTypeStatsRequest{}
	mi := &file_proto_accountType_accountType_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountTypeStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountTypeStatsRequest) ProtoMessage() {}

func (x *AccountTypeStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accountType_accountType_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountTypeStatsRequest.ProtoReflect.Descriptor instead.
func (*AccountTypeStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_accountType_accountType_proto_rawDescGZIP(), []int{13}
}

func (x *AccountTypeStatsRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type AccountTypeStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *Stats                 `protobuf:"bytes,1,opt,name=Stats,proto3" json:"Stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountTypeStatsResponse) Reset() {
	*x = AccountTypeStatsResponse{}
	mi := &file_proto_accountType_accountType_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountTypeStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountTypeStatsResponse) ProtoMessage() {}

func (x *AccountTypeStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accountType_accountType_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountTypeStatsResponse.ProtoReflect.Descriptor instead.
func (*AccountTypeStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_accountType_accountType_proto_rawDescGZIP(), []int{14}
}

func (x *AccountTypeStatsResponse) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_proto_accountType_accountType_proto protoreflect.FileDescriptor

const file_proto_accountType_accountType_proto_rawDesc = "" +
	"\n" +
	"#proto/accountType/accountType.proto\x12\vaccountType\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdf\x02\n" +
	"\vAccountType\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\"\n" +
	"\fSerialNumber\x18\x02 \x01(\x05R\fSerialNumber\x12\x14\n" +
	"\x05Title\x18\x03 \x01(\tR\x05Title\x128\n" +
	"\tCreatedAt\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x12\x1c\n" +
	"\tCreatedBy\x18\x05 \x01(\tR\tCreatedBy\x128\n" +
	"\tUpdatedAt\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12\x1c\n" +
	"\tUpdatedBy\x18\a \x01(\tR\tUpdatedBy\x128\n" +
	"\tDeletedAt\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tDeletedAt\x12\x1c\n" +
	"\tDeletedBy\x18\t \x01(\tR\tDeletedBy\"\x84\x01\n" +
	"\x06Filter\x12\x16\n" +
	"\x06Offset\x18\x01 \x01(\x05R\x06Offset\x12\x14\n" +
	"\x05Limit\x18\x02 \x01(\x05R\x05Limit\x12\x16\n" +
	"\x06SortBy\x18\x03 \x01(\tR\x06SortBy\x12\x14\n" +
	"\x05Order\x18\x04 \x01(\tR\x05Order\x12\x1e\n" +
	"\n" +
	"SearchTerm\x18\x05 \x01(\tR\n" +
	"SearchTerm\"?\n" +
	"\x05Stats\x12\x14\n" +
	"\x05Count\x18\x01 \x01(\x05R\x05Count\x12 \n" +
	"\vTotalAmount\x18\x02 \x01(\x02R\vTotalAmount\"H\n" +
	"\x18CreateAccountTypeRequest\x12,\n" +
	"\x04Acct\x18\x01 \x01(\v2\x18.accountType.AccountTypeR\x04Acct\"+\n" +
	"\x19CreateAccountTypeResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"E\n" +
	"\x15GetAccountTypeRequest\x12,\n" +
	"\x04Acct\x18\x01 \x01(\v2\x18.accountType.AccountTypeR\x04Acct\"F\n" +
	"\x16GetAccountTypeResponse\x12,\n" +
	"\x04Acct\x18\x01 \x01(\v2\x18.accountType.AccountTypeR\x04Acct\"H\n" +
	"\x18UpdateAccountTypeRequest\x12,\n" +
	"\x04Acct\x18\x01 \x01(\v2\x18.accountType.AccountTypeR\x04Acct\"I\n" +
	"\x19UpdateAccountTypeResponse\x12,\n" +
	"\x04Acct\x18\x01 \x01(\v2\x18.accountType.AccountTypeR\x04Acct\"H\n" +
	"\x18DeleteAccountTypeRequest\x12,\n" +
	"\x04Acct\x18\x01 \x01(\v2\x18.accountType.AccountTypeR\x04Acct\"\x1b\n" +
	"\x19DeleteAccountTypeResponse\"E\n" +
	"\x16ListAccountTypeRequest\x12+\n" +
	"\x06Filter\x18\x01 \x01(\v2\x13.accountType.FilterR\x06Filter\"G\n" +
	"\x17ListAccountTypeResponse\x12,\n" +
	"\x04Acct\x18\x01 \x03(\v2\x18.accountType.AccountTypeR\x04Acct\"F\n" +
	"\x17AccountTypeStatsRequest\x12+\n" +
	"\x06Filter\x18\x01 \x01(\v2\x13.accountType.FilterR\x06Filter\"D\n" +
	"\x18AccountTypeStatsResponse\x12(\n" +
	"\x05Stats\x18\x01 \x01(\v2\x12.accountType.StatsR\x05Stats2\xe6\x04\n" +
	"\x12AccountTypeService\x12d\n" +
	"\x11CreateAccountType\x12%.accountType.CreateAccountTypeRequest\x1a&.accountType.CreateAccountTypeResponse\"\x00\x12[\n" +
	"\x0eGetAccountType\x12\".accountType.GetAccountTypeRequest\x1a#.accountType.GetAccountTypeResponse\"\x00\x12d\n" +
	"\x11UpdateAccountType\x12%.accountType.UpdateAccountTypeRequest\x1a&.accountType.UpdateAccountTypeResponse\"\x00\x12d\n" +
	"\x11DeleteAccountType\x12%.accountType.DeleteAccountTypeRequest\x1a&.accountType.DeleteAccountTypeResponse\"\x00\x12^\n" +
	"\x0fListAccountType\x12#.accountType.ListAccountTypeRequest\x1a$.accountType.ListAccountTypeResponse\"\x00\x12a\n" +
	"\x10AccountTypeStats\x12$.accountType.AccountTypeStatsRequest\x1a%.accountType.AccountTypeStatsResponse\"\x00B\x15Z\x13./proto/accountTypeb\x06proto3"

var (
	file_proto_accountType_accountType_proto_rawDescOnce sync.Once
	file_proto_accountType_accountType_proto_rawDescData []byte
)

func file_proto_accountType_accountType_proto_rawDescGZIP() []byte {
	file_proto_accountType_accountType_proto_rawDescOnce.Do(func() {
		file_proto_accountType_accountType_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_accountType_accountType_proto_rawDesc), len(file_proto_accountType_accountType_proto_rawDesc)))
	})
	return file_proto_accountType_accountType_proto_rawDescData
}

var file_proto_accountType_accountType_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_accountType_accountType_proto_goTypes = []any{
	(*AccountType)(nil),               // 0: accountType.AccountType
	(*Filter)(nil),                    // 1: accountType.Filter
	(*Stats)(nil),                     // 2: accountType.Stats
	(*CreateAccountTypeRequest)(nil),  // 3: accountType.CreateAccountTypeRequest
	(*CreateAccountTypeResponse)(nil), // 4: accountType.CreateAccountTypeResponse
	(*GetAccountTypeRequest)(nil),     // 5: accountType.GetAccountTypeRequest
	(*GetAccountTypeResponse)(nil),    // 6: accountType.GetAccountTypeResponse
	(*UpdateAccountTypeRequest)(nil),  // 7: accountType.UpdateAccountTypeRequest
	(*UpdateAccountTypeResponse)(nil), // 8: accountType.UpdateAccountTypeResponse
	(*DeleteAccountTypeRequest)(nil),  // 9: accountType.DeleteAccountTypeRequest
	(*DeleteAccountTypeResponse)(nil), // 10: accountType.DeleteAccountTypeResponse
	(*ListAccountTypeRequest)(nil),    // 11: accountType.ListAccountTypeRequest
	(*ListAccountTypeResponse)(nil),   // 12: accountType.ListAccountTypeResponse
	(*AccountTypeStatsRequest)(nil),   // 13: accountType.AccountTypeStatsRequest
	(*AccountTypeStatsResponse)(nil),  // 14: accountType.AccountTypeStatsResponse
	(*timestamppb.Timestamp)(nil),     // 15: google.protobuf.Timestamp
}
var file_proto_accountType_accountType_proto_depIdxs = []int32{
	15, // 0: accountType.AccountType.CreatedAt:type_name -> google.protobuf.Timestamp
	15, // 1: accountType.AccountType.UpdatedAt:type_name -> google.protobuf.Timestamp
	15, // 2: accountType.AccountType.DeletedAt:type_name -> google.protobuf.Timestamp
	0,  // 3: accountType.CreateAccountTypeRequest.Acct:type_name -> accountType.AccountType
	0,  // 4: accountType.GetAccountTypeRequest.Acct:type_name -> accountType.AccountType
	0,  // 5: accountType.GetAccountTypeResponse.Acct:type_name -> accountType.AccountType
	0,  // 6: accountType.UpdateAccountTypeRequest.Acct:type_name -> accountType.AccountType
	0,  // 7: accountType.UpdateAccountTypeResponse.Acct:type_name -> accountType.AccountType
	0,  // 8: accountType.DeleteAccountTypeRequest.Acct:type_name -> accountType.AccountType
	1,  // 9: accountType.ListAccountTypeRequest.Filter:type_name -> accountType.Filter
	0,  // 10: accountType.ListAccountTypeResponse.Acct:type_name -> accountType.AccountType
	1,  // 11: accountType.AccountTypeStatsRequest.Filter:type_name -> accountType.Filter
	2,  // 12: accountType.AccountTypeStatsResponse.Stats:type_name -> accountType.Stats
	3,  // 13: accountType.AccountTypeService.CreateAccountType:input_type -> accountType.CreateAccountTypeRequest
	5,  // 14: accountType.AccountTypeService.GetAccountType:input_type -> accountType.GetAccountTypeRequest
	7,  // 15: accountType.AccountTypeService.UpdateAccountType:input_type -> accountType.UpdateAccountTypeRequest
	9,  // 16: accountType.AccountTypeService.DeleteAccountType:input_type -> accountType.DeleteAccountTypeRequest
	11, // 17: accountType.AccountTypeService.ListAccountType:input_type -> accountType.ListAccountTypeRequest
	13, // 18: accountType.AccountTypeService.AccountTypeStats:input_type -> accountType.AccountTypeStatsRequest
	4,  // 19: accountType.AccountTypeService.CreateAccountType:output_type -> accountType.CreateAccountTypeResponse
	6,  // 20: accountType.AccountTypeService.GetAccountType:output_type -> accountType.GetAccountTypeResponse
	8,  // 21: accountType.AccountTypeService.UpdateAccountType:output_type -> accountType.UpdateAccountTypeResponse
	10, // 22: accountType.AccountTypeService.DeleteAccountType:output_type -> accountType.DeleteAccountTypeResponse
	12, // 23: accountType.AccountTypeService.ListAccountType:output_type -> accountType.ListAccountTypeResponse
	14, // 24: accountType.AccountTypeService.AccountTypeStats:output_type -> accountType.AccountTypeStatsResponse
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_accountType_accountType_proto_init() }
func file_proto_accountType_accountType_proto_init() {
	if File_proto_accountType_accountType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_accountType_accountType_proto_rawDesc), len(file_proto_accountType_accountType_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_accountType_accountType_proto_goTypes,
		DependencyIndexes: file_proto_accountType_accountType_proto_depIdxs,
		MessageInfos:      file_proto_accountType_accountType_proto_msgTypes,
	}.Build()
	File_proto_accountType_accountType_proto = out.File
	file_proto_accountType_accountType_proto_goTypes = nil
	file_proto_accountType_accountType_proto_depIdxs = nil
}
