// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/accountType/accountType.proto

package accountType

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountTypeService_CreateAccountType_FullMethodName = "/accountType.AccountTypeService/CreateAccountType"
	AccountTypeService_GetAccountType_FullMethodName    = "/accountType.AccountTypeService/GetAccountType"
	AccountTypeService_UpdateAccountType_FullMethodName = "/accountType.AccountTypeService/UpdateAccountType"
	AccountTypeService_DeleteAccountType_FullMethodName = "/accountType.AccountTypeService/DeleteAccountType"
	AccountTypeService_ListAccountType_FullMethodName   = "/accountType.AccountTypeService/ListAccountType"
	AccountTypeService_AccountTypeStats_FullMethodName  = "/accountType.AccountTypeService/AccountTypeStats"
)

// AccountTypeServiceClient is the client API for AccountTypeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountTypeServiceClient interface {
	CreateAccountType(ctx context.Context, in *CreateAccountTypeRequest, opts ...grpc.CallOption) (*CreateAccountTypeResponse, error)
	GetAccountType(ctx context.Context, in *GetAccountTypeRequest, opts ...grpc.CallOption) (*GetAccountTypeResponse, error)
	UpdateAccountType(ctx context.Context, in *UpdateAccountTypeRequest, opts ...grpc.CallOption) (*UpdateAccountTypeResponse, error)
	DeleteAccountType(ctx context.Context, in *DeleteAccountTypeRequest, opts ...grpc.CallOption) (*DeleteAccountTypeResponse, error)
	ListAccountType(ctx context.Context, in *ListAccountTypeRequest, opts ...grpc.CallOption) (*ListAccountTypeResponse, error)
	AccountTypeStats(ctx context.Context, in *AccountTypeStatsRequest, opts ...grpc.CallOption) (*AccountTypeStatsResponse, error)
}

type accountTypeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountTypeServiceClient(cc grpc.ClientConnInterface) AccountTypeServiceClient {
	return &accountTypeServiceClient{cc}
}

func (c *accountTypeServiceClient) CreateAccountType(ctx context.Context, in *CreateAccountTypeRequest, opts ...grpc.CallOption) (*CreateAccountTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAccountTypeResponse)
	err := c.cc.Invoke(ctx, AccountTypeService_CreateAccountType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountTypeServiceClient) GetAccountType(ctx context.Context, in *GetAccountTypeRequest, opts ...grpc.CallOption) (*GetAccountTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountTypeResponse)
	err := c.cc.Invoke(ctx, AccountTypeService_GetAccountType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountTypeServiceClient) UpdateAccountType(ctx context.Context, in *UpdateAccountTypeRequest, opts ...grpc.CallOption) (*UpdateAccountTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateAccountTypeResponse)
	err := c.cc.Invoke(ctx, AccountTypeService_UpdateAccountType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountTypeServiceClient) DeleteAccountType(ctx context.Context, in *DeleteAccountTypeRequest, opts ...grpc.CallOption) (*DeleteAccountTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAccountTypeResponse)
	err := c.cc.Invoke(ctx, AccountTypeService_DeleteAccountType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountTypeServiceClient) ListAccountType(ctx context.Context, in *ListAccountTypeRequest, opts ...grpc.CallOption) (*ListAccountTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAccountTypeResponse)
	err := c.cc.Invoke(ctx, AccountTypeService_ListAccountType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountTypeServiceClient) AccountTypeStats(ctx context.Context, in *AccountTypeStatsRequest, opts ...grpc.CallOption) (*AccountTypeStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AccountTypeStatsResponse)
	err := c.cc.Invoke(ctx, AccountTypeService_AccountTypeStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountTypeServiceServer is the server API for AccountTypeService service.
// All implementations must embed UnimplementedAccountTypeServiceServer
// for forward compatibility.
type AccountTypeServiceServer interface {
	CreateAccountType(context.Context, *CreateAccountTypeRequest) (*CreateAccountTypeResponse, error)
	GetAccountType(context.Context, *GetAccountTypeRequest) (*GetAccountTypeResponse, error)
	UpdateAccountType(context.Context, *UpdateAccountTypeRequest) (*UpdateAccountTypeResponse, error)
	DeleteAccountType(context.Context, *DeleteAccountTypeRequest) (*DeleteAccountTypeResponse, error)
	ListAccountType(context.Context, *ListAccountTypeRequest) (*ListAccountTypeResponse, error)
	AccountTypeStats(context.Context, *AccountTypeStatsRequest) (*AccountTypeStatsResponse, error)
	mustEmbedUnimplementedAccountTypeServiceServer()
}

// UnimplementedAccountTypeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountTypeServiceServer struct{}

func (UnimplementedAccountTypeServiceServer) CreateAccountType(context.Context, *CreateAccountTypeRequest) (*CreateAccountTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccountType not implemented")
}
func (UnimplementedAccountTypeServiceServer) GetAccountType(context.Context, *GetAccountTypeRequest) (*GetAccountTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccountType not implemented")
}
func (UnimplementedAccountTypeServiceServer) UpdateAccountType(context.Context, *UpdateAccountTypeRequest) (*UpdateAccountTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAccountType not implemented")
}
func (UnimplementedAccountTypeServiceServer) DeleteAccountType(context.Context, *DeleteAccountTypeRequest) (*DeleteAccountTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAccountType not implemented")
}
func (UnimplementedAccountTypeServiceServer) ListAccountType(context.Context, *ListAccountTypeRequest) (*ListAccountTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAccountType not implemented")
}
func (UnimplementedAccountTypeServiceServer) AccountTypeStats(context.Context, *AccountTypeStatsRequest) (*AccountTypeStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AccountTypeStats not implemented")
}
func (UnimplementedAccountTypeServiceServer) mustEmbedUnimplementedAccountTypeServiceServer() {}
func (UnimplementedAccountTypeServiceServer) testEmbeddedByValue()                            {}

// UnsafeAccountTypeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountTypeServiceServer will
// result in compilation errors.
type UnsafeAccountTypeServiceServer interface {
	mustEmbedUnimplementedAccountTypeServiceServer()
}

func RegisterAccountTypeServiceServer(s grpc.ServiceRegistrar, srv AccountTypeServiceServer) {
	// If the following call pancis, it indicates UnimplementedAccountTypeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountTypeService_ServiceDesc, srv)
}

func _AccountTypeService_CreateAccountType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountTypeServiceServer).CreateAccountType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountTypeService_CreateAccountType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountTypeServiceServer).CreateAccountType(ctx, req.(*CreateAccountTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountTypeService_GetAccountType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountTypeServiceServer).GetAccountType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountTypeService_GetAccountType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountTypeServiceServer).GetAccountType(ctx, req.(*GetAccountTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountTypeService_UpdateAccountType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccountTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountTypeServiceServer).UpdateAccountType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountTypeService_UpdateAccountType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountTypeServiceServer).UpdateAccountType(ctx, req.(*UpdateAccountTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountTypeService_DeleteAccountType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAccountTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountTypeServiceServer).DeleteAccountType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountTypeService_DeleteAccountType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountTypeServiceServer).DeleteAccountType(ctx, req.(*DeleteAccountTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountTypeService_ListAccountType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountTypeServiceServer).ListAccountType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountTypeService_ListAccountType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountTypeServiceServer).ListAccountType(ctx, req.(*ListAccountTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountTypeService_AccountTypeStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AccountTypeStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountTypeServiceServer).AccountTypeStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountTypeService_AccountTypeStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountTypeServiceServer).AccountTypeStats(ctx, req.(*AccountTypeStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountTypeService_ServiceDesc is the grpc.ServiceDesc for AccountTypeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountTypeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accountType.AccountTypeService",
	HandlerType: (*AccountTypeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccountType",
			Handler:    _AccountTypeService_CreateAccountType_Handler,
		},
		{
			MethodName: "GetAccountType",
			Handler:    _AccountTypeService_GetAccountType_Handler,
		},
		{
			MethodName: "UpdateAccountType",
			Handler:    _AccountTypeService_UpdateAccountType_Handler,
		},
		{
			MethodName: "DeleteAccountType",
			Handler:    _AccountTypeService_DeleteAccountType_Handler,
		},
		{
			MethodName: "ListAccountType",
			Handler:    _AccountTypeService_ListAccountType_Handler,
		},
		{
			MethodName: "AccountTypeStats",
			Handler:    _AccountTypeService_AccountTypeStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/accountType/accountType.proto",
}
