// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/accounts/accounts.proto

package accounts

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Accounts struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	SerialNumber  int32                  `protobuf:"varint,2,opt,name=SerialNumber,proto3" json:"SerialNumber,omitempty"`
	AccountType   string                 `protobuf:"bytes,3,opt,name=AccountType,proto3" json:"AccountType,omitempty"`
	Details       string                 `protobuf:"bytes,4,opt,name=Details,proto3" json:"Details,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,6,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,8,opt,name=UpdatedBy,proto3" json:"UpdatedBy,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`
	DeletedBy     string                 `protobuf:"bytes,10,opt,name=DeletedBy,proto3" json:"DeletedBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Accounts) Reset() {
	*x = Accounts{}
	mi := &file_proto_accounts_accounts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Accounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Accounts) ProtoMessage() {}

func (x *Accounts) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_accounts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Accounts.ProtoReflect.Descriptor instead.
func (*Accounts) Descriptor() ([]byte, []int) {
	return file_proto_accounts_accounts_proto_rawDescGZIP(), []int{0}
}

func (x *Accounts) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Accounts) GetSerialNumber() int32 {
	if x != nil {
		return x.SerialNumber
	}
	return 0
}

func (x *Accounts) GetAccountType() string {
	if x != nil {
		return x.AccountType
	}
	return ""
}

func (x *Accounts) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *Accounts) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Accounts) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Accounts) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Accounts) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Accounts) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Accounts) GetDeletedBy() string {
	if x != nil {
		return x.DeletedBy
	}
	return ""
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	SortBy        string                 `protobuf:"bytes,3,opt,name=SortBy,proto3" json:"SortBy,omitempty"`
	Order         string                 `protobuf:"bytes,4,opt,name=Order,proto3" json:"Order,omitempty"`
	SearchTerm    string                 `protobuf:"bytes,5,opt,name=SearchTerm,proto3" json:"SearchTerm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_proto_accounts_accounts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_accounts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_proto_accounts_accounts_proto_rawDescGZIP(), []int{1}
}

func (x *Filter) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Filter) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Filter) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *Filter) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *Filter) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

type Stats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_proto_accounts_accounts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_accounts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_proto_accounts_accounts_proto_rawDescGZIP(), []int{2}
}

func (x *Stats) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CreateAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acnt          *Accounts              `protobuf:"bytes,1,opt,name=Acnt,proto3" json:"Acnt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountsRequest) Reset() {
	*x = CreateAccountsRequest{}
	mi := &file_proto_accounts_accounts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountsRequest) ProtoMessage() {}

func (x *CreateAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_accounts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountsRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountsRequest) Descriptor() ([]byte, []int) {
	return file_proto_accounts_accounts_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAccountsRequest) GetAcnt() *Accounts {
	if x != nil {
		return x.Acnt
	}
	return nil
}

type CreateAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountsResponse) Reset() {
	*x = CreateAccountsResponse{}
	mi := &file_proto_accounts_accounts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountsResponse) ProtoMessage() {}

func (x *CreateAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_accounts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountsResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountsResponse) Descriptor() ([]byte, []int) {
	return file_proto_accounts_accounts_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAccountsResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acnt          *Accounts              `protobuf:"bytes,1,opt,name=Acnt,proto3" json:"Acnt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountsRequest) Reset() {
	*x = GetAccountsRequest{}
	mi := &file_proto_accounts_accounts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountsRequest) ProtoMessage() {}

func (x *GetAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_accounts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountsRequest.ProtoReflect.Descriptor instead.
func (*GetAccountsRequest) Descriptor() ([]byte, []int) {
	return file_proto_accounts_accounts_proto_rawDescGZIP(), []int{5}
}

func (x *GetAccountsRequest) GetAcnt() *Accounts {
	if x != nil {
		return x.Acnt
	}
	return nil
}

type GetAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acnt          *Accounts              `protobuf:"bytes,1,opt,name=Acnt,proto3" json:"Acnt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountsResponse) Reset() {
	*x = GetAccountsResponse{}
	mi := &file_proto_accounts_accounts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountsResponse) ProtoMessage() {}

func (x *GetAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_accounts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountsResponse.ProtoReflect.Descriptor instead.
func (*GetAccountsResponse) Descriptor() ([]byte, []int) {
	return file_proto_accounts_accounts_proto_rawDescGZIP(), []int{6}
}

func (x *GetAccountsResponse) GetAcnt() *Accounts {
	if x != nil {
		return x.Acnt
	}
	return nil
}

type UpdateAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acnt          *Accounts              `protobuf:"bytes,1,opt,name=Acnt,proto3" json:"Acnt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountsRequest) Reset() {
	*x = UpdateAccountsRequest{}
	mi := &file_proto_accounts_accounts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountsRequest) ProtoMessage() {}

func (x *UpdateAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_accounts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountsRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountsRequest) Descriptor() ([]byte, []int) {
	return file_proto_accounts_accounts_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAccountsRequest) GetAcnt() *Accounts {
	if x != nil {
		return x.Acnt
	}
	return nil
}

type UpdateAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acnt          *Accounts              `protobuf:"bytes,1,opt,name=Acnt,proto3" json:"Acnt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountsResponse) Reset() {
	*x = UpdateAccountsResponse{}
	mi := &file_proto_accounts_accounts_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountsResponse) ProtoMessage() {}

func (x *UpdateAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_accounts_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountsResponse.ProtoReflect.Descriptor instead.
func (*UpdateAccountsResponse) Descriptor() ([]byte, []int) {
	return file_proto_accounts_accounts_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateAccountsResponse) GetAcnt() *Accounts {
	if x != nil {
		return x.Acnt
	}
	return nil
}

type DeleteAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acnt          *Accounts              `protobuf:"bytes,1,opt,name=Acnt,proto3" json:"Acnt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountsRequest) Reset() {
	*x = DeleteAccountsRequest{}
	mi := &file_proto_accounts_accounts_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountsRequest) ProtoMessage() {}

func (x *DeleteAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_accounts_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountsRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountsRequest) Descriptor() ([]byte, []int) {
	return file_proto_accounts_accounts_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteAccountsRequest) GetAcnt() *Accounts {
	if x != nil {
		return x.Acnt
	}
	return nil
}

type DeleteAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountsResponse) Reset() {
	*x = DeleteAccountsResponse{}
	mi := &file_proto_accounts_accounts_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountsResponse) ProtoMessage() {}

func (x *DeleteAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_accounts_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountsResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccountsResponse) Descriptor() ([]byte, []int) {
	return file_proto_accounts_accounts_proto_rawDescGZIP(), []int{10}
}

type ListAccountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=Filter,proto3" json:"Filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsRequest) Reset() {
	*x = ListAccountsRequest{}
	mi := &file_proto_accounts_accounts_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsRequest) ProtoMessage() {}

func (x *ListAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_accounts_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsRequest.ProtoReflect.Descriptor instead.
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return file_proto_accounts_accounts_proto_rawDescGZIP(), []int{11}
}

func (x *ListAccountsRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acnt          []*Accounts            `protobuf:"bytes,1,rep,name=Acnt,proto3" json:"Acnt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsResponse) Reset() {
	*x = ListAccountsResponse{}
	mi := &file_proto_accounts_accounts_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsResponse) ProtoMessage() {}

func (x *ListAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_accounts_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return file_proto_accounts_accounts_proto_rawDescGZIP(), []int{12}
}

func (x *ListAccountsResponse) GetAcnt() []*Accounts {
	if x != nil {
		return x.Acnt
	}
	return nil
}

type AccountsStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=Filter,proto3" json:"Filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountsStatsRequest) Reset() {
	*x = AccountsStatsRequest{}
	mi := &file_proto_accounts_accounts_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountsStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountsStatsRequest) ProtoMessage() {}

func (x *AccountsStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_accounts_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountsStatsRequest.ProtoReflect.Descriptor instead.
func (*AccountsStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_accounts_accounts_proto_rawDescGZIP(), []int{13}
}

func (x *AccountsStatsRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type AccountsStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *Stats                 `protobuf:"bytes,1,opt,name=Stats,proto3" json:"Stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountsStatsResponse) Reset() {
	*x = AccountsStatsResponse{}
	mi := &file_proto_accounts_accounts_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountsStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountsStatsResponse) ProtoMessage() {}

func (x *AccountsStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accounts_accounts_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountsStatsResponse.ProtoReflect.Descriptor instead.
func (*AccountsStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_accounts_accounts_proto_rawDescGZIP(), []int{14}
}

func (x *AccountsStatsResponse) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_proto_accounts_accounts_proto protoreflect.FileDescriptor

const file_proto_accounts_accounts_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/accounts/accounts.proto\x12\baccounts\x1a\x1fgoogle/protobuf/timestamp.proto\"\x82\x03\n" +
	"\bAccounts\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\"\n" +
	"\fSerialNumber\x18\x02 \x01(\x05R\fSerialNumber\x12 \n" +
	"\vAccountType\x18\x03 \x01(\tR\vAccountType\x12\x18\n" +
	"\aDetails\x18\x04 \x01(\tR\aDetails\x128\n" +
	"\tCreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x12\x1c\n" +
	"\tCreatedBy\x18\x06 \x01(\tR\tCreatedBy\x128\n" +
	"\tUpdatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12\x1c\n" +
	"\tUpdatedBy\x18\b \x01(\tR\tUpdatedBy\x128\n" +
	"\tDeletedAt\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tDeletedAt\x12\x1c\n" +
	"\tDeletedBy\x18\n" +
	" \x01(\tR\tDeletedBy\"\x84\x01\n" +
	"\x06Filter\x12\x16\n" +
	"\x06Offset\x18\x01 \x01(\x05R\x06Offset\x12\x14\n" +
	"\x05Limit\x18\x02 \x01(\x05R\x05Limit\x12\x16\n" +
	"\x06SortBy\x18\x03 \x01(\tR\x06SortBy\x12\x14\n" +
	"\x05Order\x18\x04 \x01(\tR\x05Order\x12\x1e\n" +
	"\n" +
	"SearchTerm\x18\x05 \x01(\tR\n" +
	"SearchTerm\"\x1d\n" +
	"\x05Stats\x12\x14\n" +
	"\x05Count\x18\x01 \x01(\x05R\x05Count\"?\n" +
	"\x15CreateAccountsRequest\x12&\n" +
	"\x04Acnt\x18\x01 \x01(\v2\x12.accounts.AccountsR\x04Acnt\"(\n" +
	"\x16CreateAccountsResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"<\n" +
	"\x12GetAccountsRequest\x12&\n" +
	"\x04Acnt\x18\x01 \x01(\v2\x12.accounts.AccountsR\x04Acnt\"=\n" +
	"\x13GetAccountsResponse\x12&\n" +
	"\x04Acnt\x18\x01 \x01(\v2\x12.accounts.AccountsR\x04Acnt\"?\n" +
	"\x15UpdateAccountsRequest\x12&\n" +
	"\x04Acnt\x18\x01 \x01(\v2\x12.accounts.AccountsR\x04Acnt\"@\n" +
	"\x16UpdateAccountsResponse\x12&\n" +
	"\x04Acnt\x18\x01 \x01(\v2\x12.accounts.AccountsR\x04Acnt\"?\n" +
	"\x15DeleteAccountsRequest\x12&\n" +
	"\x04Acnt\x18\x01 \x01(\v2\x12.accounts.AccountsR\x04Acnt\"\x18\n" +
	"\x16DeleteAccountsResponse\"?\n" +
	"\x13ListAccountsRequest\x12(\n" +
	"\x06Filter\x18\x01 \x01(\v2\x10.accounts.FilterR\x06Filter\">\n" +
	"\x14ListAccountsResponse\x12&\n" +
	"\x04Acnt\x18\x01 \x03(\v2\x12.accounts.AccountsR\x04Acnt\"@\n" +
	"\x14AccountsStatsRequest\x12(\n" +
	"\x06Filter\x18\x01 \x01(\v2\x10.accounts.FilterR\x06Filter\">\n" +
	"\x15AccountsStatsResponse\x12%\n" +
	"\x05Stats\x18\x01 \x01(\v2\x0f.accounts.StatsR\x05Stats2\x89\x04\n" +
	"\x0fAccountsService\x12U\n" +
	"\x0eCreateAccounts\x12\x1f.accounts.CreateAccountsRequest\x1a .accounts.CreateAccountsResponse\"\x00\x12L\n" +
	"\vGetAccounts\x12\x1c.accounts.GetAccountsRequest\x1a\x1d.accounts.GetAccountsResponse\"\x00\x12U\n" +
	"\x0eUpdateAccounts\x12\x1f.accounts.UpdateAccountsRequest\x1a .accounts.UpdateAccountsResponse\"\x00\x12U\n" +
	"\x0eDeleteAccounts\x12\x1f.accounts.DeleteAccountsRequest\x1a .accounts.DeleteAccountsResponse\"\x00\x12O\n" +
	"\fListAccounts\x12\x1d.accounts.ListAccountsRequest\x1a\x1e.accounts.ListAccountsResponse\"\x00\x12R\n" +
	"\rAccountsStats\x12\x1e.accounts.AccountsStatsRequest\x1a\x1f.accounts.AccountsStatsResponse\"\x00B\x12Z\x10./proto/accountsb\x06proto3"

var (
	file_proto_accounts_accounts_proto_rawDescOnce sync.Once
	file_proto_accounts_accounts_proto_rawDescData []byte
)

func file_proto_accounts_accounts_proto_rawDescGZIP() []byte {
	file_proto_accounts_accounts_proto_rawDescOnce.Do(func() {
		file_proto_accounts_accounts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_accounts_accounts_proto_rawDesc), len(file_proto_accounts_accounts_proto_rawDesc)))
	})
	return file_proto_accounts_accounts_proto_rawDescData
}

var file_proto_accounts_accounts_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_accounts_accounts_proto_goTypes = []any{
	(*Accounts)(nil),               // 0: accounts.Accounts
	(*Filter)(nil),                 // 1: accounts.Filter
	(*Stats)(nil),                  // 2: accounts.Stats
	(*CreateAccountsRequest)(nil),  // 3: accounts.CreateAccountsRequest
	(*CreateAccountsResponse)(nil), // 4: accounts.CreateAccountsResponse
	(*GetAccountsRequest)(nil),     // 5: accounts.GetAccountsRequest
	(*GetAccountsResponse)(nil),    // 6: accounts.GetAccountsResponse
	(*UpdateAccountsRequest)(nil),  // 7: accounts.UpdateAccountsRequest
	(*UpdateAccountsResponse)(nil), // 8: accounts.UpdateAccountsResponse
	(*DeleteAccountsRequest)(nil),  // 9: accounts.DeleteAccountsRequest
	(*DeleteAccountsResponse)(nil), // 10: accounts.DeleteAccountsResponse
	(*ListAccountsRequest)(nil),    // 11: accounts.ListAccountsRequest
	(*ListAccountsResponse)(nil),   // 12: accounts.ListAccountsResponse
	(*AccountsStatsRequest)(nil),   // 13: accounts.AccountsStatsRequest
	(*AccountsStatsResponse)(nil),  // 14: accounts.AccountsStatsResponse
	(*timestamppb.Timestamp)(nil),  // 15: google.protobuf.Timestamp
}
var file_proto_accounts_accounts_proto_depIdxs = []int32{
	15, // 0: accounts.Accounts.CreatedAt:type_name -> google.protobuf.Timestamp
	15, // 1: accounts.Accounts.UpdatedAt:type_name -> google.protobuf.Timestamp
	15, // 2: accounts.Accounts.DeletedAt:type_name -> google.protobuf.Timestamp
	0,  // 3: accounts.CreateAccountsRequest.Acnt:type_name -> accounts.Accounts
	0,  // 4: accounts.GetAccountsRequest.Acnt:type_name -> accounts.Accounts
	0,  // 5: accounts.GetAccountsResponse.Acnt:type_name -> accounts.Accounts
	0,  // 6: accounts.UpdateAccountsRequest.Acnt:type_name -> accounts.Accounts
	0,  // 7: accounts.UpdateAccountsResponse.Acnt:type_name -> accounts.Accounts
	0,  // 8: accounts.DeleteAccountsRequest.Acnt:type_name -> accounts.Accounts
	1,  // 9: accounts.ListAccountsRequest.Filter:type_name -> accounts.Filter
	0,  // 10: accounts.ListAccountsResponse.Acnt:type_name -> accounts.Accounts
	1,  // 11: accounts.AccountsStatsRequest.Filter:type_name -> accounts.Filter
	2,  // 12: accounts.AccountsStatsResponse.Stats:type_name -> accounts.Stats
	3,  // 13: accounts.AccountsService.CreateAccounts:input_type -> accounts.CreateAccountsRequest
	5,  // 14: accounts.AccountsService.GetAccounts:input_type -> accounts.GetAccountsRequest
	7,  // 15: accounts.AccountsService.UpdateAccounts:input_type -> accounts.UpdateAccountsRequest
	9,  // 16: accounts.AccountsService.DeleteAccounts:input_type -> accounts.DeleteAccountsRequest
	11, // 17: accounts.AccountsService.ListAccounts:input_type -> accounts.ListAccountsRequest
	13, // 18: accounts.AccountsService.AccountsStats:input_type -> accounts.AccountsStatsRequest
	4,  // 19: accounts.AccountsService.CreateAccounts:output_type -> accounts.CreateAccountsResponse
	6,  // 20: accounts.AccountsService.GetAccounts:output_type -> accounts.GetAccountsResponse
	8,  // 21: accounts.AccountsService.UpdateAccounts:output_type -> accounts.UpdateAccountsResponse
	10, // 22: accounts.AccountsService.DeleteAccounts:output_type -> accounts.DeleteAccountsResponse
	12, // 23: accounts.AccountsService.ListAccounts:output_type -> accounts.ListAccountsResponse
	14, // 24: accounts.AccountsService.AccountsStats:output_type -> accounts.AccountsStatsResponse
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_accounts_accounts_proto_init() }
func file_proto_accounts_accounts_proto_init() {
	if File_proto_accounts_accounts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_accounts_accounts_proto_rawDesc), len(file_proto_accounts_accounts_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_accounts_accounts_proto_goTypes,
		DependencyIndexes: file_proto_accounts_accounts_proto_depIdxs,
		MessageInfos:      file_proto_accounts_accounts_proto_msgTypes,
	}.Build()
	File_proto_accounts_accounts_proto = out.File
	file_proto_accounts_accounts_proto_goTypes = nil
	file_proto_accounts_accounts_proto_depIdxs = nil
}
