// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/currency/currency.proto

package currency

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	SerialNumber  int32                  `protobuf:"varint,2,opt,name=SerialNumber,proto3" json:"SerialNumber,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	ExchangeRate  int32                  `protobuf:"varint,4,opt,name=ExchangeRate,proto3" json:"ExchangeRate,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,6,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,8,opt,name=UpdatedBy,proto3" json:"UpdatedBy,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`
	DeletedBy     string                 `protobuf:"bytes,10,opt,name=DeletedBy,proto3" json:"DeletedBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Currency) Reset() {
	*x = Currency{}
	mi := &file_proto_currency_currency_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currency) ProtoMessage() {}

func (x *Currency) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currency.ProtoReflect.Descriptor instead.
func (*Currency) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{0}
}

func (x *Currency) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Currency) GetSerialNumber() int32 {
	if x != nil {
		return x.SerialNumber
	}
	return 0
}

func (x *Currency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Currency) GetExchangeRate() int32 {
	if x != nil {
		return x.ExchangeRate
	}
	return 0
}

func (x *Currency) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Currency) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Currency) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Currency) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Currency) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Currency) GetDeletedBy() string {
	if x != nil {
		return x.DeletedBy
	}
	return ""
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	SortBy        string                 `protobuf:"bytes,3,opt,name=SortBy,proto3" json:"SortBy,omitempty"`
	Order         string                 `protobuf:"bytes,4,opt,name=Order,proto3" json:"Order,omitempty"`
	SearchTerm    string                 `protobuf:"bytes,5,opt,name=SearchTerm,proto3" json:"SearchTerm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_proto_currency_currency_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{1}
}

func (x *Filter) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Filter) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Filter) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *Filter) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *Filter) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

type Stats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	TotalAmount   int32                  `protobuf:"varint,2,opt,name=TotalAmount,proto3" json:"TotalAmount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_proto_currency_currency_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{2}
}

func (x *Stats) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Stats) GetTotalAmount() int32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

type CreateCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Curr          *Currency              `protobuf:"bytes,1,opt,name=Curr,proto3" json:"Curr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCurrencyRequest) Reset() {
	*x = CreateCurrencyRequest{}
	mi := &file_proto_currency_currency_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCurrencyRequest) ProtoMessage() {}

func (x *CreateCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCurrencyRequest.ProtoReflect.Descriptor instead.
func (*CreateCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCurrencyRequest) GetCurr() *Currency {
	if x != nil {
		return x.Curr
	}
	return nil
}

type CreateCurrencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCurrencyResponse) Reset() {
	*x = CreateCurrencyResponse{}
	mi := &file_proto_currency_currency_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCurrencyResponse) ProtoMessage() {}

func (x *CreateCurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCurrencyResponse.ProtoReflect.Descriptor instead.
func (*CreateCurrencyResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCurrencyResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Curr          *Currency              `protobuf:"bytes,1,opt,name=Curr,proto3" json:"Curr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrencyRequest) Reset() {
	*x = GetCurrencyRequest{}
	mi := &file_proto_currency_currency_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrencyRequest) ProtoMessage() {}

func (x *GetCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrencyRequest.ProtoReflect.Descriptor instead.
func (*GetCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{5}
}

func (x *GetCurrencyRequest) GetCurr() *Currency {
	if x != nil {
		return x.Curr
	}
	return nil
}

type GetCurrencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Curr          *Currency              `protobuf:"bytes,1,opt,name=Curr,proto3" json:"Curr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrencyResponse) Reset() {
	*x = GetCurrencyResponse{}
	mi := &file_proto_currency_currency_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrencyResponse) ProtoMessage() {}

func (x *GetCurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrencyResponse.ProtoReflect.Descriptor instead.
func (*GetCurrencyResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{6}
}

func (x *GetCurrencyResponse) GetCurr() *Currency {
	if x != nil {
		return x.Curr
	}
	return nil
}

type UpdateCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Curr          *Currency              `protobuf:"bytes,1,opt,name=Curr,proto3" json:"Curr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCurrencyRequest) Reset() {
	*x = UpdateCurrencyRequest{}
	mi := &file_proto_currency_currency_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCurrencyRequest) ProtoMessage() {}

func (x *UpdateCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCurrencyRequest.ProtoReflect.Descriptor instead.
func (*UpdateCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCurrencyRequest) GetCurr() *Currency {
	if x != nil {
		return x.Curr
	}
	return nil
}

type UpdateCurrencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Curr          *Currency              `protobuf:"bytes,1,opt,name=Curr,proto3" json:"Curr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCurrencyResponse) Reset() {
	*x = UpdateCurrencyResponse{}
	mi := &file_proto_currency_currency_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCurrencyResponse) ProtoMessage() {}

func (x *UpdateCurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCurrencyResponse.ProtoReflect.Descriptor instead.
func (*UpdateCurrencyResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCurrencyResponse) GetCurr() *Currency {
	if x != nil {
		return x.Curr
	}
	return nil
}

type DeleteCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Curr          *Currency              `protobuf:"bytes,1,opt,name=Curr,proto3" json:"Curr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCurrencyRequest) Reset() {
	*x = DeleteCurrencyRequest{}
	mi := &file_proto_currency_currency_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCurrencyRequest) ProtoMessage() {}

func (x *DeleteCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCurrencyRequest.ProtoReflect.Descriptor instead.
func (*DeleteCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCurrencyRequest) GetCurr() *Currency {
	if x != nil {
		return x.Curr
	}
	return nil
}

type DeleteCurrencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCurrencyResponse) Reset() {
	*x = DeleteCurrencyResponse{}
	mi := &file_proto_currency_currency_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCurrencyResponse) ProtoMessage() {}

func (x *DeleteCurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCurrencyResponse.ProtoReflect.Descriptor instead.
func (*DeleteCurrencyResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{10}
}

type ListCurrencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=Filter,proto3" json:"Filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCurrencyRequest) Reset() {
	*x = ListCurrencyRequest{}
	mi := &file_proto_currency_currency_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCurrencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCurrencyRequest) ProtoMessage() {}

func (x *ListCurrencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCurrencyRequest.ProtoReflect.Descriptor instead.
func (*ListCurrencyRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{11}
}

func (x *ListCurrencyRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListCurrencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Curr          []*Currency            `protobuf:"bytes,1,rep,name=Curr,proto3" json:"Curr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCurrencyResponse) Reset() {
	*x = ListCurrencyResponse{}
	mi := &file_proto_currency_currency_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCurrencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCurrencyResponse) ProtoMessage() {}

func (x *ListCurrencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCurrencyResponse.ProtoReflect.Descriptor instead.
func (*ListCurrencyResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{12}
}

func (x *ListCurrencyResponse) GetCurr() []*Currency {
	if x != nil {
		return x.Curr
	}
	return nil
}

type CurrencyStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=Filter,proto3" json:"Filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrencyStatsRequest) Reset() {
	*x = CurrencyStatsRequest{}
	mi := &file_proto_currency_currency_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyStatsRequest) ProtoMessage() {}

func (x *CurrencyStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyStatsRequest.ProtoReflect.Descriptor instead.
func (*CurrencyStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{13}
}

func (x *CurrencyStatsRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type CurrencyStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *Stats                 `protobuf:"bytes,1,opt,name=Stats,proto3" json:"Stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrencyStatsResponse) Reset() {
	*x = CurrencyStatsResponse{}
	mi := &file_proto_currency_currency_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyStatsResponse) ProtoMessage() {}

func (x *CurrencyStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_currency_currency_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyStatsResponse.ProtoReflect.Descriptor instead.
func (*CurrencyStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_currency_currency_proto_rawDescGZIP(), []int{14}
}

func (x *CurrencyStatsResponse) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_proto_currency_currency_proto protoreflect.FileDescriptor

const file_proto_currency_currency_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/currency/currency.proto\x12\bcurrency\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfe\x02\n" +
	"\bCurrency\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\"\n" +
	"\fSerialNumber\x18\x02 \x01(\x05R\fSerialNumber\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\"\n" +
	"\fExchangeRate\x18\x04 \x01(\x05R\fExchangeRate\x128\n" +
	"\tCreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x12\x1c\n" +
	"\tCreatedBy\x18\x06 \x01(\tR\tCreatedBy\x128\n" +
	"\tUpdatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12\x1c\n" +
	"\tUpdatedBy\x18\b \x01(\tR\tUpdatedBy\x128\n" +
	"\tDeletedAt\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tDeletedAt\x12\x1c\n" +
	"\tDeletedBy\x18\n" +
	" \x01(\tR\tDeletedBy\"\x84\x01\n" +
	"\x06Filter\x12\x16\n" +
	"\x06Offset\x18\x01 \x01(\x05R\x06Offset\x12\x14\n" +
	"\x05Limit\x18\x02 \x01(\x05R\x05Limit\x12\x16\n" +
	"\x06SortBy\x18\x03 \x01(\tR\x06SortBy\x12\x14\n" +
	"\x05Order\x18\x04 \x01(\tR\x05Order\x12\x1e\n" +
	"\n" +
	"SearchTerm\x18\x05 \x01(\tR\n" +
	"SearchTerm\"?\n" +
	"\x05Stats\x12\x14\n" +
	"\x05Count\x18\x01 \x01(\x05R\x05Count\x12 \n" +
	"\vTotalAmount\x18\x02 \x01(\x05R\vTotalAmount\"?\n" +
	"\x15CreateCurrencyRequest\x12&\n" +
	"\x04Curr\x18\x01 \x01(\v2\x12.currency.CurrencyR\x04Curr\"(\n" +
	"\x16CreateCurrencyResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"<\n" +
	"\x12GetCurrencyRequest\x12&\n" +
	"\x04Curr\x18\x01 \x01(\v2\x12.currency.CurrencyR\x04Curr\"=\n" +
	"\x13GetCurrencyResponse\x12&\n" +
	"\x04Curr\x18\x01 \x01(\v2\x12.currency.CurrencyR\x04Curr\"?\n" +
	"\x15UpdateCurrencyRequest\x12&\n" +
	"\x04Curr\x18\x01 \x01(\v2\x12.currency.CurrencyR\x04Curr\"@\n" +
	"\x16UpdateCurrencyResponse\x12&\n" +
	"\x04Curr\x18\x01 \x01(\v2\x12.currency.CurrencyR\x04Curr\"?\n" +
	"\x15DeleteCurrencyRequest\x12&\n" +
	"\x04Curr\x18\x01 \x01(\v2\x12.currency.CurrencyR\x04Curr\"\x18\n" +
	"\x16DeleteCurrencyResponse\"?\n" +
	"\x13ListCurrencyRequest\x12(\n" +
	"\x06Filter\x18\x01 \x01(\v2\x10.currency.FilterR\x06Filter\">\n" +
	"\x14ListCurrencyResponse\x12&\n" +
	"\x04Curr\x18\x01 \x03(\v2\x12.currency.CurrencyR\x04Curr\"@\n" +
	"\x14CurrencyStatsRequest\x12(\n" +
	"\x06Filter\x18\x01 \x01(\v2\x10.currency.FilterR\x06Filter\">\n" +
	"\x15CurrencyStatsResponse\x12%\n" +
	"\x05Stats\x18\x01 \x01(\v2\x0f.currency.StatsR\x05Stats2\x89\x04\n" +
	"\x0fCurrencyService\x12U\n" +
	"\x0eCreateCurrency\x12\x1f.currency.CreateCurrencyRequest\x1a .currency.CreateCurrencyResponse\"\x00\x12L\n" +
	"\vGetCurrency\x12\x1c.currency.GetCurrencyRequest\x1a\x1d.currency.GetCurrencyResponse\"\x00\x12U\n" +
	"\x0eUpdateCurrency\x12\x1f.currency.UpdateCurrencyRequest\x1a .currency.UpdateCurrencyResponse\"\x00\x12U\n" +
	"\x0eDeleteCurrency\x12\x1f.currency.DeleteCurrencyRequest\x1a .currency.DeleteCurrencyResponse\"\x00\x12O\n" +
	"\fListCurrency\x12\x1d.currency.ListCurrencyRequest\x1a\x1e.currency.ListCurrencyResponse\"\x00\x12R\n" +
	"\rCurrencyStats\x12\x1e.currency.CurrencyStatsRequest\x1a\x1f.currency.CurrencyStatsResponse\"\x00B\x12Z\x10./proto/currencyb\x06proto3"

var (
	file_proto_currency_currency_proto_rawDescOnce sync.Once
	file_proto_currency_currency_proto_rawDescData []byte
)

func file_proto_currency_currency_proto_rawDescGZIP() []byte {
	file_proto_currency_currency_proto_rawDescOnce.Do(func() {
		file_proto_currency_currency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_currency_currency_proto_rawDesc), len(file_proto_currency_currency_proto_rawDesc)))
	})
	return file_proto_currency_currency_proto_rawDescData
}

var file_proto_currency_currency_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_currency_currency_proto_goTypes = []any{
	(*Currency)(nil),               // 0: currency.Currency
	(*Filter)(nil),                 // 1: currency.Filter
	(*Stats)(nil),                  // 2: currency.Stats
	(*CreateCurrencyRequest)(nil),  // 3: currency.CreateCurrencyRequest
	(*CreateCurrencyResponse)(nil), // 4: currency.CreateCurrencyResponse
	(*GetCurrencyRequest)(nil),     // 5: currency.GetCurrencyRequest
	(*GetCurrencyResponse)(nil),    // 6: currency.GetCurrencyResponse
	(*UpdateCurrencyRequest)(nil),  // 7: currency.UpdateCurrencyRequest
	(*UpdateCurrencyResponse)(nil), // 8: currency.UpdateCurrencyResponse
	(*DeleteCurrencyRequest)(nil),  // 9: currency.DeleteCurrencyRequest
	(*DeleteCurrencyResponse)(nil), // 10: currency.DeleteCurrencyResponse
	(*ListCurrencyRequest)(nil),    // 11: currency.ListCurrencyRequest
	(*ListCurrencyResponse)(nil),   // 12: currency.ListCurrencyResponse
	(*CurrencyStatsRequest)(nil),   // 13: currency.CurrencyStatsRequest
	(*CurrencyStatsResponse)(nil),  // 14: currency.CurrencyStatsResponse
	(*timestamppb.Timestamp)(nil),  // 15: google.protobuf.Timestamp
}
var file_proto_currency_currency_proto_depIdxs = []int32{
	15, // 0: currency.Currency.CreatedAt:type_name -> google.protobuf.Timestamp
	15, // 1: currency.Currency.UpdatedAt:type_name -> google.protobuf.Timestamp
	15, // 2: currency.Currency.DeletedAt:type_name -> google.protobuf.Timestamp
	0,  // 3: currency.CreateCurrencyRequest.Curr:type_name -> currency.Currency
	0,  // 4: currency.GetCurrencyRequest.Curr:type_name -> currency.Currency
	0,  // 5: currency.GetCurrencyResponse.Curr:type_name -> currency.Currency
	0,  // 6: currency.UpdateCurrencyRequest.Curr:type_name -> currency.Currency
	0,  // 7: currency.UpdateCurrencyResponse.Curr:type_name -> currency.Currency
	0,  // 8: currency.DeleteCurrencyRequest.Curr:type_name -> currency.Currency
	1,  // 9: currency.ListCurrencyRequest.Filter:type_name -> currency.Filter
	0,  // 10: currency.ListCurrencyResponse.Curr:type_name -> currency.Currency
	1,  // 11: currency.CurrencyStatsRequest.Filter:type_name -> currency.Filter
	2,  // 12: currency.CurrencyStatsResponse.Stats:type_name -> currency.Stats
	3,  // 13: currency.CurrencyService.CreateCurrency:input_type -> currency.CreateCurrencyRequest
	5,  // 14: currency.CurrencyService.GetCurrency:input_type -> currency.GetCurrencyRequest
	7,  // 15: currency.CurrencyService.UpdateCurrency:input_type -> currency.UpdateCurrencyRequest
	9,  // 16: currency.CurrencyService.DeleteCurrency:input_type -> currency.DeleteCurrencyRequest
	11, // 17: currency.CurrencyService.ListCurrency:input_type -> currency.ListCurrencyRequest
	13, // 18: currency.CurrencyService.CurrencyStats:input_type -> currency.CurrencyStatsRequest
	4,  // 19: currency.CurrencyService.CreateCurrency:output_type -> currency.CreateCurrencyResponse
	6,  // 20: currency.CurrencyService.GetCurrency:output_type -> currency.GetCurrencyResponse
	8,  // 21: currency.CurrencyService.UpdateCurrency:output_type -> currency.UpdateCurrencyResponse
	10, // 22: currency.CurrencyService.DeleteCurrency:output_type -> currency.DeleteCurrencyResponse
	12, // 23: currency.CurrencyService.ListCurrency:output_type -> currency.ListCurrencyResponse
	14, // 24: currency.CurrencyService.CurrencyStats:output_type -> currency.CurrencyStatsResponse
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_currency_currency_proto_init() }
func file_proto_currency_currency_proto_init() {
	if File_proto_currency_currency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_currency_currency_proto_rawDesc), len(file_proto_currency_currency_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_currency_currency_proto_goTypes,
		DependencyIndexes: file_proto_currency_currency_proto_depIdxs,
		MessageInfos:      file_proto_currency_currency_proto_msgTypes,
	}.Build()
	File_proto_currency_currency_proto = out.File
	file_proto_currency_currency_proto_goTypes = nil
	file_proto_currency_currency_proto_depIdxs = nil
}
