// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/medDocs/medDocs.proto

package medDocs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MedDocs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	SerialNumber  int32                  `protobuf:"varint,2,opt,name=SerialNumber,proto3" json:"SerialNumber,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	UploadedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=UploadedAt,proto3" json:"UploadedAt,omitempty"`
	UploadedBy    string                 `protobuf:"bytes,6,opt,name=UploadedBy,proto3" json:"UploadedBy,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`
	DeletedBy     string                 `protobuf:"bytes,8,opt,name=DeletedBy,proto3" json:"DeletedBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MedDocs) Reset() {
	*x = MedDocs{}
	mi := &file_proto_medDocs_medDocs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MedDocs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MedDocs) ProtoMessage() {}

func (x *MedDocs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medDocs_medDocs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MedDocs.ProtoReflect.Descriptor instead.
func (*MedDocs) Descriptor() ([]byte, []int) {
	return file_proto_medDocs_medDocs_proto_rawDescGZIP(), []int{0}
}

func (x *MedDocs) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *MedDocs) GetSerialNumber() int32 {
	if x != nil {
		return x.SerialNumber
	}
	return 0
}

func (x *MedDocs) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MedDocs) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MedDocs) GetUploadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadedAt
	}
	return nil
}

func (x *MedDocs) GetUploadedBy() string {
	if x != nil {
		return x.UploadedBy
	}
	return ""
}

func (x *MedDocs) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *MedDocs) GetDeletedBy() string {
	if x != nil {
		return x.DeletedBy
	}
	return ""
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	SortBy        string                 `protobuf:"bytes,3,opt,name=SortBy,proto3" json:"SortBy,omitempty"`
	Order         string                 `protobuf:"bytes,4,opt,name=Order,proto3" json:"Order,omitempty"`
	SearchTerm    string                 `protobuf:"bytes,5,opt,name=SearchTerm,proto3" json:"SearchTerm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_proto_medDocs_medDocs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medDocs_medDocs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_proto_medDocs_medDocs_proto_rawDescGZIP(), []int{1}
}

func (x *Filter) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Filter) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Filter) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *Filter) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *Filter) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

type Stats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_proto_medDocs_medDocs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medDocs_medDocs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_proto_medDocs_medDocs_proto_rawDescGZIP(), []int{2}
}

func (x *Stats) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CreateMedDocsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Docs          *MedDocs               `protobuf:"bytes,1,opt,name=Docs,proto3" json:"Docs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMedDocsRequest) Reset() {
	*x = CreateMedDocsRequest{}
	mi := &file_proto_medDocs_medDocs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMedDocsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMedDocsRequest) ProtoMessage() {}

func (x *CreateMedDocsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medDocs_medDocs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMedDocsRequest.ProtoReflect.Descriptor instead.
func (*CreateMedDocsRequest) Descriptor() ([]byte, []int) {
	return file_proto_medDocs_medDocs_proto_rawDescGZIP(), []int{3}
}

func (x *CreateMedDocsRequest) GetDocs() *MedDocs {
	if x != nil {
		return x.Docs
	}
	return nil
}

type CreateMedDocsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMedDocsResponse) Reset() {
	*x = CreateMedDocsResponse{}
	mi := &file_proto_medDocs_medDocs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMedDocsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMedDocsResponse) ProtoMessage() {}

func (x *CreateMedDocsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medDocs_medDocs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMedDocsResponse.ProtoReflect.Descriptor instead.
func (*CreateMedDocsResponse) Descriptor() ([]byte, []int) {
	return file_proto_medDocs_medDocs_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMedDocsResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetMedDocsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Docs          *MedDocs               `protobuf:"bytes,1,opt,name=Docs,proto3" json:"Docs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMedDocsRequest) Reset() {
	*x = GetMedDocsRequest{}
	mi := &file_proto_medDocs_medDocs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMedDocsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedDocsRequest) ProtoMessage() {}

func (x *GetMedDocsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medDocs_medDocs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedDocsRequest.ProtoReflect.Descriptor instead.
func (*GetMedDocsRequest) Descriptor() ([]byte, []int) {
	return file_proto_medDocs_medDocs_proto_rawDescGZIP(), []int{5}
}

func (x *GetMedDocsRequest) GetDocs() *MedDocs {
	if x != nil {
		return x.Docs
	}
	return nil
}

type GetMedDocsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Docs          *MedDocs               `protobuf:"bytes,1,opt,name=Docs,proto3" json:"Docs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMedDocsResponse) Reset() {
	*x = GetMedDocsResponse{}
	mi := &file_proto_medDocs_medDocs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMedDocsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMedDocsResponse) ProtoMessage() {}

func (x *GetMedDocsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medDocs_medDocs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMedDocsResponse.ProtoReflect.Descriptor instead.
func (*GetMedDocsResponse) Descriptor() ([]byte, []int) {
	return file_proto_medDocs_medDocs_proto_rawDescGZIP(), []int{6}
}

func (x *GetMedDocsResponse) GetDocs() *MedDocs {
	if x != nil {
		return x.Docs
	}
	return nil
}

type DeleteMedDocsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Docs          *MedDocs               `protobuf:"bytes,1,opt,name=Docs,proto3" json:"Docs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMedDocsRequest) Reset() {
	*x = DeleteMedDocsRequest{}
	mi := &file_proto_medDocs_medDocs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMedDocsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMedDocsRequest) ProtoMessage() {}

func (x *DeleteMedDocsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medDocs_medDocs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMedDocsRequest.ProtoReflect.Descriptor instead.
func (*DeleteMedDocsRequest) Descriptor() ([]byte, []int) {
	return file_proto_medDocs_medDocs_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteMedDocsRequest) GetDocs() *MedDocs {
	if x != nil {
		return x.Docs
	}
	return nil
}

type DeleteMedDocsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMedDocsResponse) Reset() {
	*x = DeleteMedDocsResponse{}
	mi := &file_proto_medDocs_medDocs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMedDocsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMedDocsResponse) ProtoMessage() {}

func (x *DeleteMedDocsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medDocs_medDocs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMedDocsResponse.ProtoReflect.Descriptor instead.
func (*DeleteMedDocsResponse) Descriptor() ([]byte, []int) {
	return file_proto_medDocs_medDocs_proto_rawDescGZIP(), []int{8}
}

type ListMedDocsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=Filter,proto3" json:"Filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMedDocsRequest) Reset() {
	*x = ListMedDocsRequest{}
	mi := &file_proto_medDocs_medDocs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMedDocsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMedDocsRequest) ProtoMessage() {}

func (x *ListMedDocsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medDocs_medDocs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMedDocsRequest.ProtoReflect.Descriptor instead.
func (*ListMedDocsRequest) Descriptor() ([]byte, []int) {
	return file_proto_medDocs_medDocs_proto_rawDescGZIP(), []int{9}
}

func (x *ListMedDocsRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListMedDocsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Docs          []*MedDocs             `protobuf:"bytes,1,rep,name=Docs,proto3" json:"Docs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMedDocsResponse) Reset() {
	*x = ListMedDocsResponse{}
	mi := &file_proto_medDocs_medDocs_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMedDocsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMedDocsResponse) ProtoMessage() {}

func (x *ListMedDocsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medDocs_medDocs_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMedDocsResponse.ProtoReflect.Descriptor instead.
func (*ListMedDocsResponse) Descriptor() ([]byte, []int) {
	return file_proto_medDocs_medDocs_proto_rawDescGZIP(), []int{10}
}

func (x *ListMedDocsResponse) GetDocs() []*MedDocs {
	if x != nil {
		return x.Docs
	}
	return nil
}

type MedDocsStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=Filter,proto3" json:"Filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MedDocsStatsRequest) Reset() {
	*x = MedDocsStatsRequest{}
	mi := &file_proto_medDocs_medDocs_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MedDocsStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MedDocsStatsRequest) ProtoMessage() {}

func (x *MedDocsStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medDocs_medDocs_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MedDocsStatsRequest.ProtoReflect.Descriptor instead.
func (*MedDocsStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_medDocs_medDocs_proto_rawDescGZIP(), []int{11}
}

func (x *MedDocsStatsRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type MedDocsStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *Stats                 `protobuf:"bytes,1,opt,name=Stats,proto3" json:"Stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MedDocsStatsResponse) Reset() {
	*x = MedDocsStatsResponse{}
	mi := &file_proto_medDocs_medDocs_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MedDocsStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MedDocsStatsResponse) ProtoMessage() {}

func (x *MedDocsStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medDocs_medDocs_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MedDocsStatsResponse.ProtoReflect.Descriptor instead.
func (*MedDocsStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_medDocs_medDocs_proto_rawDescGZIP(), []int{12}
}

func (x *MedDocsStatsResponse) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_proto_medDocs_medDocs_proto protoreflect.FileDescriptor

const file_proto_medDocs_medDocs_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/medDocs/medDocs.proto\x12\amedDocs\x1a\x1fgoogle/protobuf/timestamp.proto\"\x99\x02\n" +
	"\aMedDocs\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\"\n" +
	"\fSerialNumber\x18\x02 \x01(\x05R\fSerialNumber\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x12\n" +
	"\x04Type\x18\x04 \x01(\tR\x04Type\x12:\n" +
	"\n" +
	"UploadedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"UploadedAt\x12\x1e\n" +
	"\n" +
	"UploadedBy\x18\x06 \x01(\tR\n" +
	"UploadedBy\x128\n" +
	"\tDeletedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tDeletedAt\x12\x1c\n" +
	"\tDeletedBy\x18\b \x01(\tR\tDeletedBy\"\x84\x01\n" +
	"\x06Filter\x12\x16\n" +
	"\x06Offset\x18\x01 \x01(\x05R\x06Offset\x12\x14\n" +
	"\x05Limit\x18\x02 \x01(\x05R\x05Limit\x12\x16\n" +
	"\x06SortBy\x18\x03 \x01(\tR\x06SortBy\x12\x14\n" +
	"\x05Order\x18\x04 \x01(\tR\x05Order\x12\x1e\n" +
	"\n" +
	"SearchTerm\x18\x05 \x01(\tR\n" +
	"SearchTerm\"\x1d\n" +
	"\x05Stats\x12\x14\n" +
	"\x05Count\x18\x01 \x01(\x05R\x05Count\"<\n" +
	"\x14CreateMedDocsRequest\x12$\n" +
	"\x04Docs\x18\x01 \x01(\v2\x10.medDocs.MedDocsR\x04Docs\"'\n" +
	"\x15CreateMedDocsResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"9\n" +
	"\x11GetMedDocsRequest\x12$\n" +
	"\x04Docs\x18\x01 \x01(\v2\x10.medDocs.MedDocsR\x04Docs\":\n" +
	"\x12GetMedDocsResponse\x12$\n" +
	"\x04Docs\x18\x01 \x01(\v2\x10.medDocs.MedDocsR\x04Docs\"<\n" +
	"\x14DeleteMedDocsRequest\x12$\n" +
	"\x04Docs\x18\x01 \x01(\v2\x10.medDocs.MedDocsR\x04Docs\"\x17\n" +
	"\x15DeleteMedDocsResponse\"=\n" +
	"\x12ListMedDocsRequest\x12'\n" +
	"\x06Filter\x18\x01 \x01(\v2\x0f.medDocs.FilterR\x06Filter\";\n" +
	"\x13ListMedDocsResponse\x12$\n" +
	"\x04Docs\x18\x01 \x03(\v2\x10.medDocs.MedDocsR\x04Docs\">\n" +
	"\x13MedDocsStatsRequest\x12'\n" +
	"\x06Filter\x18\x01 \x01(\v2\x0f.medDocs.FilterR\x06Filter\"<\n" +
	"\x14MedDocsStatsResponse\x12$\n" +
	"\x05Stats\x18\x01 \x01(\v2\x0e.medDocs.StatsR\x05Stats2\x98\x03\n" +
	"\x0eMedDocsService\x12P\n" +
	"\rCreateMedDocs\x12\x1d.medDocs.CreateMedDocsRequest\x1a\x1e.medDocs.CreateMedDocsResponse\"\x00\x12G\n" +
	"\n" +
	"GetMedDocs\x12\x1a.medDocs.GetMedDocsRequest\x1a\x1b.medDocs.GetMedDocsResponse\"\x00\x12P\n" +
	"\rDeleteMedDocs\x12\x1d.medDocs.DeleteMedDocsRequest\x1a\x1e.medDocs.DeleteMedDocsResponse\"\x00\x12J\n" +
	"\vListMedDocs\x12\x1b.medDocs.ListMedDocsRequest\x1a\x1c.medDocs.ListMedDocsResponse\"\x00\x12M\n" +
	"\fMedDocsStats\x12\x1c.medDocs.MedDocsStatsRequest\x1a\x1d.medDocs.MedDocsStatsResponse\"\x00B\x11Z\x0f./proto/medDocsb\x06proto3"

var (
	file_proto_medDocs_medDocs_proto_rawDescOnce sync.Once
	file_proto_medDocs_medDocs_proto_rawDescData []byte
)

func file_proto_medDocs_medDocs_proto_rawDescGZIP() []byte {
	file_proto_medDocs_medDocs_proto_rawDescOnce.Do(func() {
		file_proto_medDocs_medDocs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_medDocs_medDocs_proto_rawDesc), len(file_proto_medDocs_medDocs_proto_rawDesc)))
	})
	return file_proto_medDocs_medDocs_proto_rawDescData
}

var file_proto_medDocs_medDocs_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_medDocs_medDocs_proto_goTypes = []any{
	(*MedDocs)(nil),               // 0: medDocs.MedDocs
	(*Filter)(nil),                // 1: medDocs.Filter
	(*Stats)(nil),                 // 2: medDocs.Stats
	(*CreateMedDocsRequest)(nil),  // 3: medDocs.CreateMedDocsRequest
	(*CreateMedDocsResponse)(nil), // 4: medDocs.CreateMedDocsResponse
	(*GetMedDocsRequest)(nil),     // 5: medDocs.GetMedDocsRequest
	(*GetMedDocsResponse)(nil),    // 6: medDocs.GetMedDocsResponse
	(*DeleteMedDocsRequest)(nil),  // 7: medDocs.DeleteMedDocsRequest
	(*DeleteMedDocsResponse)(nil), // 8: medDocs.DeleteMedDocsResponse
	(*ListMedDocsRequest)(nil),    // 9: medDocs.ListMedDocsRequest
	(*ListMedDocsResponse)(nil),   // 10: medDocs.ListMedDocsResponse
	(*MedDocsStatsRequest)(nil),   // 11: medDocs.MedDocsStatsRequest
	(*MedDocsStatsResponse)(nil),  // 12: medDocs.MedDocsStatsResponse
	(*timestamppb.Timestamp)(nil), // 13: google.protobuf.Timestamp
}
var file_proto_medDocs_medDocs_proto_depIdxs = []int32{
	13, // 0: medDocs.MedDocs.UploadedAt:type_name -> google.protobuf.Timestamp
	13, // 1: medDocs.MedDocs.DeletedAt:type_name -> google.protobuf.Timestamp
	0,  // 2: medDocs.CreateMedDocsRequest.Docs:type_name -> medDocs.MedDocs
	0,  // 3: medDocs.GetMedDocsRequest.Docs:type_name -> medDocs.MedDocs
	0,  // 4: medDocs.GetMedDocsResponse.Docs:type_name -> medDocs.MedDocs
	0,  // 5: medDocs.DeleteMedDocsRequest.Docs:type_name -> medDocs.MedDocs
	1,  // 6: medDocs.ListMedDocsRequest.Filter:type_name -> medDocs.Filter
	0,  // 7: medDocs.ListMedDocsResponse.Docs:type_name -> medDocs.MedDocs
	1,  // 8: medDocs.MedDocsStatsRequest.Filter:type_name -> medDocs.Filter
	2,  // 9: medDocs.MedDocsStatsResponse.Stats:type_name -> medDocs.Stats
	3,  // 10: medDocs.MedDocsService.CreateMedDocs:input_type -> medDocs.CreateMedDocsRequest
	5,  // 11: medDocs.MedDocsService.GetMedDocs:input_type -> medDocs.GetMedDocsRequest
	7,  // 12: medDocs.MedDocsService.DeleteMedDocs:input_type -> medDocs.DeleteMedDocsRequest
	9,  // 13: medDocs.MedDocsService.ListMedDocs:input_type -> medDocs.ListMedDocsRequest
	11, // 14: medDocs.MedDocsService.MedDocsStats:input_type -> medDocs.MedDocsStatsRequest
	4,  // 15: medDocs.MedDocsService.CreateMedDocs:output_type -> medDocs.CreateMedDocsResponse
	6,  // 16: medDocs.MedDocsService.GetMedDocs:output_type -> medDocs.GetMedDocsResponse
	8,  // 17: medDocs.MedDocsService.DeleteMedDocs:output_type -> medDocs.DeleteMedDocsResponse
	10, // 18: medDocs.MedDocsService.ListMedDocs:output_type -> medDocs.ListMedDocsResponse
	12, // 19: medDocs.MedDocsService.MedDocsStats:output_type -> medDocs.MedDocsStatsResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_medDocs_medDocs_proto_init() }
func file_proto_medDocs_medDocs_proto_init() {
	if File_proto_medDocs_medDocs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_medDocs_medDocs_proto_rawDesc), len(file_proto_medDocs_medDocs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_medDocs_medDocs_proto_goTypes,
		DependencyIndexes: file_proto_medDocs_medDocs_proto_depIdxs,
		MessageInfos:      file_proto_medDocs_medDocs_proto_msgTypes,
	}.Build()
	File_proto_medDocs_medDocs_proto = out.File
	file_proto_medDocs_medDocs_proto_goTypes = nil
	file_proto_medDocs_medDocs_proto_depIdxs = nil
}
