// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: proto/medDocs/medDocs.proto

package medDocs

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MedDocsService_CreateMedDocs_FullMethodName = "/medDocs.MedDocsService/CreateMedDocs"
	MedDocsService_GetMedDocs_FullMethodName    = "/medDocs.MedDocsService/GetMedDocs"
	MedDocsService_DeleteMedDocs_FullMethodName = "/medDocs.MedDocsService/DeleteMedDocs"
	MedDocsService_ListMedDocs_FullMethodName   = "/medDocs.MedDocsService/ListMedDocs"
	MedDocsService_MedDocsStats_FullMethodName  = "/medDocs.MedDocsService/MedDocsStats"
)

// MedDocsServiceClient is the client API for MedDocsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MedDocsServiceClient interface {
	CreateMedDocs(ctx context.Context, in *CreateMedDocsRequest, opts ...grpc.CallOption) (*CreateMedDocsResponse, error)
	GetMedDocs(ctx context.Context, in *GetMedDocsRequest, opts ...grpc.CallOption) (*GetMedDocsResponse, error)
	DeleteMedDocs(ctx context.Context, in *DeleteMedDocsRequest, opts ...grpc.CallOption) (*DeleteMedDocsResponse, error)
	ListMedDocs(ctx context.Context, in *ListMedDocsRequest, opts ...grpc.CallOption) (*ListMedDocsResponse, error)
	MedDocsStats(ctx context.Context, in *MedDocsStatsRequest, opts ...grpc.CallOption) (*MedDocsStatsResponse, error)
}

type medDocsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMedDocsServiceClient(cc grpc.ClientConnInterface) MedDocsServiceClient {
	return &medDocsServiceClient{cc}
}

func (c *medDocsServiceClient) CreateMedDocs(ctx context.Context, in *CreateMedDocsRequest, opts ...grpc.CallOption) (*CreateMedDocsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMedDocsResponse)
	err := c.cc.Invoke(ctx, MedDocsService_CreateMedDocs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *medDocsServiceClient) GetMedDocs(ctx context.Context, in *GetMedDocsRequest, opts ...grpc.CallOption) (*GetMedDocsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMedDocsResponse)
	err := c.cc.Invoke(ctx, MedDocsService_GetMedDocs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *medDocsServiceClient) DeleteMedDocs(ctx context.Context, in *DeleteMedDocsRequest, opts ...grpc.CallOption) (*DeleteMedDocsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMedDocsResponse)
	err := c.cc.Invoke(ctx, MedDocsService_DeleteMedDocs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *medDocsServiceClient) ListMedDocs(ctx context.Context, in *ListMedDocsRequest, opts ...grpc.CallOption) (*ListMedDocsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMedDocsResponse)
	err := c.cc.Invoke(ctx, MedDocsService_ListMedDocs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *medDocsServiceClient) MedDocsStats(ctx context.Context, in *MedDocsStatsRequest, opts ...grpc.CallOption) (*MedDocsStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MedDocsStatsResponse)
	err := c.cc.Invoke(ctx, MedDocsService_MedDocsStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MedDocsServiceServer is the server API for MedDocsService service.
// All implementations must embed UnimplementedMedDocsServiceServer
// for forward compatibility.
type MedDocsServiceServer interface {
	CreateMedDocs(context.Context, *CreateMedDocsRequest) (*CreateMedDocsResponse, error)
	GetMedDocs(context.Context, *GetMedDocsRequest) (*GetMedDocsResponse, error)
	DeleteMedDocs(context.Context, *DeleteMedDocsRequest) (*DeleteMedDocsResponse, error)
	ListMedDocs(context.Context, *ListMedDocsRequest) (*ListMedDocsResponse, error)
	MedDocsStats(context.Context, *MedDocsStatsRequest) (*MedDocsStatsResponse, error)
	mustEmbedUnimplementedMedDocsServiceServer()
}

// UnimplementedMedDocsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMedDocsServiceServer struct{}

func (UnimplementedMedDocsServiceServer) CreateMedDocs(context.Context, *CreateMedDocsRequest) (*CreateMedDocsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateMedDocs not implemented")
}
func (UnimplementedMedDocsServiceServer) GetMedDocs(context.Context, *GetMedDocsRequest) (*GetMedDocsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMedDocs not implemented")
}
func (UnimplementedMedDocsServiceServer) DeleteMedDocs(context.Context, *DeleteMedDocsRequest) (*DeleteMedDocsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMedDocs not implemented")
}
func (UnimplementedMedDocsServiceServer) ListMedDocs(context.Context, *ListMedDocsRequest) (*ListMedDocsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMedDocs not implemented")
}
func (UnimplementedMedDocsServiceServer) MedDocsStats(context.Context, *MedDocsStatsRequest) (*MedDocsStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MedDocsStats not implemented")
}
func (UnimplementedMedDocsServiceServer) mustEmbedUnimplementedMedDocsServiceServer() {}
func (UnimplementedMedDocsServiceServer) testEmbeddedByValue()                        {}

// UnsafeMedDocsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MedDocsServiceServer will
// result in compilation errors.
type UnsafeMedDocsServiceServer interface {
	mustEmbedUnimplementedMedDocsServiceServer()
}

func RegisterMedDocsServiceServer(s grpc.ServiceRegistrar, srv MedDocsServiceServer) {
	// If the following call pancis, it indicates UnimplementedMedDocsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MedDocsService_ServiceDesc, srv)
}

func _MedDocsService_CreateMedDocs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMedDocsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedDocsServiceServer).CreateMedDocs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MedDocsService_CreateMedDocs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedDocsServiceServer).CreateMedDocs(ctx, req.(*CreateMedDocsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MedDocsService_GetMedDocs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMedDocsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedDocsServiceServer).GetMedDocs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MedDocsService_GetMedDocs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedDocsServiceServer).GetMedDocs(ctx, req.(*GetMedDocsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MedDocsService_DeleteMedDocs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMedDocsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedDocsServiceServer).DeleteMedDocs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MedDocsService_DeleteMedDocs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedDocsServiceServer).DeleteMedDocs(ctx, req.(*DeleteMedDocsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MedDocsService_ListMedDocs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMedDocsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedDocsServiceServer).ListMedDocs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MedDocsService_ListMedDocs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedDocsServiceServer).ListMedDocs(ctx, req.(*ListMedDocsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MedDocsService_MedDocsStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MedDocsStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MedDocsServiceServer).MedDocsStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MedDocsService_MedDocsStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MedDocsServiceServer).MedDocsStats(ctx, req.(*MedDocsStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MedDocsService_ServiceDesc is the grpc.ServiceDesc for MedDocsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MedDocsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "medDocs.MedDocsService",
	HandlerType: (*MedDocsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMedDocs",
			Handler:    _MedDocsService_CreateMedDocs_Handler,
		},
		{
			MethodName: "GetMedDocs",
			Handler:    _MedDocsService_GetMedDocs_Handler,
		},
		{
			MethodName: "DeleteMedDocs",
			Handler:    _MedDocsService_DeleteMedDocs_Handler,
		},
		{
			MethodName: "ListMedDocs",
			Handler:    _MedDocsService_ListMedDocs_Handler,
		},
		{
			MethodName: "MedDocsStats",
			Handler:    _MedDocsService_MedDocsStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/medDocs/medDocs.proto",
}
