// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/links/links.proto

package links

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	SerialNumber  int32                  `protobuf:"varint,2,opt,name=SerialNumber,proto3" json:"SerialNumber,omitempty"`
	LinkText      string                 `protobuf:"bytes,3,opt,name=LinkText,proto3" json:"LinkText,omitempty"`
	LinkURL       string                 `protobuf:"bytes,4,opt,name=LinkURL,proto3" json:"LinkURL,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,6,opt,name=CreatedBy,proto3" json:"CreatedBy,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,8,opt,name=UpdatedBy,proto3" json:"UpdatedBy,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=DeletedAt,proto3" json:"DeletedAt,omitempty"`
	DeletedBy     string                 `protobuf:"bytes,10,opt,name=DeletedBy,proto3" json:"DeletedBy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_proto_links_links_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_links_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_proto_links_links_proto_rawDescGZIP(), []int{0}
}

func (x *Link) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Link) GetSerialNumber() int32 {
	if x != nil {
		return x.SerialNumber
	}
	return 0
}

func (x *Link) GetLinkText() string {
	if x != nil {
		return x.LinkText
	}
	return ""
}

func (x *Link) GetLinkURL() string {
	if x != nil {
		return x.LinkURL
	}
	return ""
}

func (x *Link) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Link) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *Link) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Link) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *Link) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *Link) GetDeletedBy() string {
	if x != nil {
		return x.DeletedBy
	}
	return ""
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int32                  `protobuf:"varint,1,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=Limit,proto3" json:"Limit,omitempty"`
	SortBy        string                 `protobuf:"bytes,3,opt,name=SortBy,proto3" json:"SortBy,omitempty"`
	Order         string                 `protobuf:"bytes,4,opt,name=Order,proto3" json:"Order,omitempty"`
	SearchTerm    string                 `protobuf:"bytes,5,opt,name=SearchTerm,proto3" json:"SearchTerm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_proto_links_links_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_links_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_proto_links_links_proto_rawDescGZIP(), []int{1}
}

func (x *Filter) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *Filter) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Filter) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *Filter) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

func (x *Filter) GetSearchTerm() string {
	if x != nil {
		return x.SearchTerm
	}
	return ""
}

type Stats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int32                  `protobuf:"varint,1,opt,name=Count,proto3" json:"Count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stats) Reset() {
	*x = Stats{}
	mi := &file_proto_links_links_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stats) ProtoMessage() {}

func (x *Stats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_links_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stats.ProtoReflect.Descriptor instead.
func (*Stats) Descriptor() ([]byte, []int) {
	return file_proto_links_links_proto_rawDescGZIP(), []int{2}
}

func (x *Stats) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type CreateLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *Link                  `protobuf:"bytes,1,opt,name=Link,proto3" json:"Link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLinkRequest) Reset() {
	*x = CreateLinkRequest{}
	mi := &file_proto_links_links_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkRequest) ProtoMessage() {}

func (x *CreateLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_links_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_links_links_proto_rawDescGZIP(), []int{3}
}

func (x *CreateLinkRequest) GetLink() *Link {
	if x != nil {
		return x.Link
	}
	return nil
}

type CreateLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLinkResponse) Reset() {
	*x = CreateLinkResponse{}
	mi := &file_proto_links_links_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkResponse) ProtoMessage() {}

func (x *CreateLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_links_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkResponse.ProtoReflect.Descriptor instead.
func (*CreateLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_links_links_proto_rawDescGZIP(), []int{4}
}

func (x *CreateLinkResponse) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

type GetLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *Link                  `protobuf:"bytes,1,opt,name=Link,proto3" json:"Link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkRequest) Reset() {
	*x = GetLinkRequest{}
	mi := &file_proto_links_links_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkRequest) ProtoMessage() {}

func (x *GetLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_links_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkRequest.ProtoReflect.Descriptor instead.
func (*GetLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_links_links_proto_rawDescGZIP(), []int{5}
}

func (x *GetLinkRequest) GetLink() *Link {
	if x != nil {
		return x.Link
	}
	return nil
}

type GetLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *Link                  `protobuf:"bytes,1,opt,name=Link,proto3" json:"Link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkResponse) Reset() {
	*x = GetLinkResponse{}
	mi := &file_proto_links_links_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkResponse) ProtoMessage() {}

func (x *GetLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_links_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkResponse.ProtoReflect.Descriptor instead.
func (*GetLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_links_links_proto_rawDescGZIP(), []int{6}
}

func (x *GetLinkResponse) GetLink() *Link {
	if x != nil {
		return x.Link
	}
	return nil
}

type UpdateLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *Link                  `protobuf:"bytes,1,opt,name=Link,proto3" json:"Link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLinkRequest) Reset() {
	*x = UpdateLinkRequest{}
	mi := &file_proto_links_links_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLinkRequest) ProtoMessage() {}

func (x *UpdateLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_links_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLinkRequest.ProtoReflect.Descriptor instead.
func (*UpdateLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_links_links_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateLinkRequest) GetLink() *Link {
	if x != nil {
		return x.Link
	}
	return nil
}

type UpdateLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *Link                  `protobuf:"bytes,1,opt,name=Link,proto3" json:"Link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLinkResponse) Reset() {
	*x = UpdateLinkResponse{}
	mi := &file_proto_links_links_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLinkResponse) ProtoMessage() {}

func (x *UpdateLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_links_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLinkResponse.ProtoReflect.Descriptor instead.
func (*UpdateLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_links_links_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateLinkResponse) GetLink() *Link {
	if x != nil {
		return x.Link
	}
	return nil
}

type DeleteLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          *Link                  `protobuf:"bytes,1,opt,name=Link,proto3" json:"Link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLinkRequest) Reset() {
	*x = DeleteLinkRequest{}
	mi := &file_proto_links_links_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLinkRequest) ProtoMessage() {}

func (x *DeleteLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_links_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLinkRequest.ProtoReflect.Descriptor instead.
func (*DeleteLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_links_links_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteLinkRequest) GetLink() *Link {
	if x != nil {
		return x.Link
	}
	return nil
}

type DeleteLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLinkResponse) Reset() {
	*x = DeleteLinkResponse{}
	mi := &file_proto_links_links_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLinkResponse) ProtoMessage() {}

func (x *DeleteLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_links_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLinkResponse.ProtoReflect.Descriptor instead.
func (*DeleteLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_links_links_proto_rawDescGZIP(), []int{10}
}

type ListLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=Filter,proto3" json:"Filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinkRequest) Reset() {
	*x = ListLinkRequest{}
	mi := &file_proto_links_links_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinkRequest) ProtoMessage() {}

func (x *ListLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_links_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinkRequest.ProtoReflect.Descriptor instead.
func (*ListLinkRequest) Descriptor() ([]byte, []int) {
	return file_proto_links_links_proto_rawDescGZIP(), []int{11}
}

func (x *ListLinkRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type ListLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Link          []*Link                `protobuf:"bytes,1,rep,name=Link,proto3" json:"Link,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinkResponse) Reset() {
	*x = ListLinkResponse{}
	mi := &file_proto_links_links_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinkResponse) ProtoMessage() {}

func (x *ListLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_links_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinkResponse.ProtoReflect.Descriptor instead.
func (*ListLinkResponse) Descriptor() ([]byte, []int) {
	return file_proto_links_links_proto_rawDescGZIP(), []int{12}
}

func (x *ListLinkResponse) GetLink() []*Link {
	if x != nil {
		return x.Link
	}
	return nil
}

type LinkStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *Filter                `protobuf:"bytes,1,opt,name=Filter,proto3" json:"Filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkStatsRequest) Reset() {
	*x = LinkStatsRequest{}
	mi := &file_proto_links_links_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkStatsRequest) ProtoMessage() {}

func (x *LinkStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_links_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkStatsRequest.ProtoReflect.Descriptor instead.
func (*LinkStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_links_links_proto_rawDescGZIP(), []int{13}
}

func (x *LinkStatsRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

type LinkStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *Stats                 `protobuf:"bytes,1,opt,name=Stats,proto3" json:"Stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkStatsResponse) Reset() {
	*x = LinkStatsResponse{}
	mi := &file_proto_links_links_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkStatsResponse) ProtoMessage() {}

func (x *LinkStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_links_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkStatsResponse.ProtoReflect.Descriptor instead.
func (*LinkStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_links_links_proto_rawDescGZIP(), []int{14}
}

func (x *LinkStatsResponse) GetStats() *Stats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_proto_links_links_proto protoreflect.FileDescriptor

const file_proto_links_links_proto_rawDesc = "" +
	"\n" +
	"\x17proto/links/links.proto\x12\x05links\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf8\x02\n" +
	"\x04Link\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\"\n" +
	"\fSerialNumber\x18\x02 \x01(\x05R\fSerialNumber\x12\x1a\n" +
	"\bLinkText\x18\x03 \x01(\tR\bLinkText\x12\x18\n" +
	"\aLinkURL\x18\x04 \x01(\tR\aLinkURL\x128\n" +
	"\tCreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\x12\x1c\n" +
	"\tCreatedBy\x18\x06 \x01(\tR\tCreatedBy\x128\n" +
	"\tUpdatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12\x1c\n" +
	"\tUpdatedBy\x18\b \x01(\tR\tUpdatedBy\x128\n" +
	"\tDeletedAt\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tDeletedAt\x12\x1c\n" +
	"\tDeletedBy\x18\n" +
	" \x01(\tR\tDeletedBy\"\x84\x01\n" +
	"\x06Filter\x12\x16\n" +
	"\x06Offset\x18\x01 \x01(\x05R\x06Offset\x12\x14\n" +
	"\x05Limit\x18\x02 \x01(\x05R\x05Limit\x12\x16\n" +
	"\x06SortBy\x18\x03 \x01(\tR\x06SortBy\x12\x14\n" +
	"\x05Order\x18\x04 \x01(\tR\x05Order\x12\x1e\n" +
	"\n" +
	"SearchTerm\x18\x05 \x01(\tR\n" +
	"SearchTerm\"\x1d\n" +
	"\x05Stats\x12\x14\n" +
	"\x05Count\x18\x01 \x01(\x05R\x05Count\"4\n" +
	"\x11CreateLinkRequest\x12\x1f\n" +
	"\x04Link\x18\x01 \x01(\v2\v.links.LinkR\x04Link\"$\n" +
	"\x12CreateLinkResponse\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\"1\n" +
	"\x0eGetLinkRequest\x12\x1f\n" +
	"\x04Link\x18\x01 \x01(\v2\v.links.LinkR\x04Link\"2\n" +
	"\x0fGetLinkResponse\x12\x1f\n" +
	"\x04Link\x18\x01 \x01(\v2\v.links.LinkR\x04Link\"4\n" +
	"\x11UpdateLinkRequest\x12\x1f\n" +
	"\x04Link\x18\x01 \x01(\v2\v.links.LinkR\x04Link\"5\n" +
	"\x12UpdateLinkResponse\x12\x1f\n" +
	"\x04Link\x18\x01 \x01(\v2\v.links.LinkR\x04Link\"4\n" +
	"\x11DeleteLinkRequest\x12\x1f\n" +
	"\x04Link\x18\x01 \x01(\v2\v.links.LinkR\x04Link\"\x14\n" +
	"\x12DeleteLinkResponse\"8\n" +
	"\x0fListLinkRequest\x12%\n" +
	"\x06Filter\x18\x01 \x01(\v2\r.links.FilterR\x06Filter\"3\n" +
	"\x10ListLinkResponse\x12\x1f\n" +
	"\x04Link\x18\x01 \x03(\v2\v.links.LinkR\x04Link\"9\n" +
	"\x10LinkStatsRequest\x12%\n" +
	"\x06Filter\x18\x01 \x01(\v2\r.links.FilterR\x06Filter\"7\n" +
	"\x11LinkStatsResponse\x12\"\n" +
	"\x05Stats\x18\x01 \x01(\v2\f.links.StatsR\x05Stats2\x99\x03\n" +
	"\vLinkService\x12C\n" +
	"\n" +
	"CreateLink\x12\x18.links.CreateLinkRequest\x1a\x19.links.CreateLinkResponse\"\x00\x12:\n" +
	"\aGetLink\x12\x15.links.GetLinkRequest\x1a\x16.links.GetLinkResponse\"\x00\x12C\n" +
	"\n" +
	"UpdateLink\x12\x18.links.UpdateLinkRequest\x1a\x19.links.UpdateLinkResponse\"\x00\x12C\n" +
	"\n" +
	"DeleteLink\x12\x18.links.DeleteLinkRequest\x1a\x19.links.DeleteLinkResponse\"\x00\x12=\n" +
	"\bListLink\x12\x16.links.ListLinkRequest\x1a\x17.links.ListLinkResponse\"\x00\x12@\n" +
	"\tLinkStats\x12\x17.links.LinkStatsRequest\x1a\x18.links.LinkStatsResponse\"\x00B\x0fZ\r./proto/linksb\x06proto3"

var (
	file_proto_links_links_proto_rawDescOnce sync.Once
	file_proto_links_links_proto_rawDescData []byte
)

func file_proto_links_links_proto_rawDescGZIP() []byte {
	file_proto_links_links_proto_rawDescOnce.Do(func() {
		file_proto_links_links_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_links_links_proto_rawDesc), len(file_proto_links_links_proto_rawDesc)))
	})
	return file_proto_links_links_proto_rawDescData
}

var file_proto_links_links_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_links_links_proto_goTypes = []any{
	(*Link)(nil),                  // 0: links.Link
	(*Filter)(nil),                // 1: links.Filter
	(*Stats)(nil),                 // 2: links.Stats
	(*CreateLinkRequest)(nil),     // 3: links.CreateLinkRequest
	(*CreateLinkResponse)(nil),    // 4: links.CreateLinkResponse
	(*GetLinkRequest)(nil),        // 5: links.GetLinkRequest
	(*GetLinkResponse)(nil),       // 6: links.GetLinkResponse
	(*UpdateLinkRequest)(nil),     // 7: links.UpdateLinkRequest
	(*UpdateLinkResponse)(nil),    // 8: links.UpdateLinkResponse
	(*DeleteLinkRequest)(nil),     // 9: links.DeleteLinkRequest
	(*DeleteLinkResponse)(nil),    // 10: links.DeleteLinkResponse
	(*ListLinkRequest)(nil),       // 11: links.ListLinkRequest
	(*ListLinkResponse)(nil),      // 12: links.ListLinkResponse
	(*LinkStatsRequest)(nil),      // 13: links.LinkStatsRequest
	(*LinkStatsResponse)(nil),     // 14: links.LinkStatsResponse
	(*timestamppb.Timestamp)(nil), // 15: google.protobuf.Timestamp
}
var file_proto_links_links_proto_depIdxs = []int32{
	15, // 0: links.Link.CreatedAt:type_name -> google.protobuf.Timestamp
	15, // 1: links.Link.UpdatedAt:type_name -> google.protobuf.Timestamp
	15, // 2: links.Link.DeletedAt:type_name -> google.protobuf.Timestamp
	0,  // 3: links.CreateLinkRequest.Link:type_name -> links.Link
	0,  // 4: links.GetLinkRequest.Link:type_name -> links.Link
	0,  // 5: links.GetLinkResponse.Link:type_name -> links.Link
	0,  // 6: links.UpdateLinkRequest.Link:type_name -> links.Link
	0,  // 7: links.UpdateLinkResponse.Link:type_name -> links.Link
	0,  // 8: links.DeleteLinkRequest.Link:type_name -> links.Link
	1,  // 9: links.ListLinkRequest.Filter:type_name -> links.Filter
	0,  // 10: links.ListLinkResponse.Link:type_name -> links.Link
	1,  // 11: links.LinkStatsRequest.Filter:type_name -> links.Filter
	2,  // 12: links.LinkStatsResponse.Stats:type_name -> links.Stats
	3,  // 13: links.LinkService.CreateLink:input_type -> links.CreateLinkRequest
	5,  // 14: links.LinkService.GetLink:input_type -> links.GetLinkRequest
	7,  // 15: links.LinkService.UpdateLink:input_type -> links.UpdateLinkRequest
	9,  // 16: links.LinkService.DeleteLink:input_type -> links.DeleteLinkRequest
	11, // 17: links.LinkService.ListLink:input_type -> links.ListLinkRequest
	13, // 18: links.LinkService.LinkStats:input_type -> links.LinkStatsRequest
	4,  // 19: links.LinkService.CreateLink:output_type -> links.CreateLinkResponse
	6,  // 20: links.LinkService.GetLink:output_type -> links.GetLinkResponse
	8,  // 21: links.LinkService.UpdateLink:output_type -> links.UpdateLinkResponse
	10, // 22: links.LinkService.DeleteLink:output_type -> links.DeleteLinkResponse
	12, // 23: links.LinkService.ListLink:output_type -> links.ListLinkResponse
	14, // 24: links.LinkService.LinkStats:output_type -> links.LinkStatsResponse
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_links_links_proto_init() }
func file_proto_links_links_proto_init() {
	if File_proto_links_links_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_links_links_proto_rawDesc), len(file_proto_links_links_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_links_links_proto_goTypes,
		DependencyIndexes: file_proto_links_links_proto_depIdxs,
		MessageInfos:      file_proto_links_links_proto_msgTypes,
	}.Build()
	File_proto_links_links_proto = out.File
	file_proto_links_links_proto_goTypes = nil
	file_proto_links_links_proto_depIdxs = nil
}
