// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/settings/settings.proto

package settings

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Settings struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	PatientName                  string                 `protobuf:"bytes,1,opt,name=PatientName,proto3" json:"PatientName,omitempty"`
	Title                        string                 `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty"`
	BannerTitle                  string                 `protobuf:"bytes,3,opt,name=BannerTitle,proto3" json:"BannerTitle,omitempty"`
	HighlightedBannerTitle       string                 `protobuf:"bytes,4,opt,name=HighlightedBannerTitle,proto3" json:"HighlightedBannerTitle,omitempty"`
	BannerDescription            string                 `protobuf:"bytes,5,opt,name=BannerDescription,proto3" json:"BannerDescription,omitempty"`
	HighlightedBannerDescription string                 `protobuf:"bytes,6,opt,name=HighlightedBannerDescription,proto3" json:"HighlightedBannerDescription,omitempty"`
	BannerImage                  string                 `protobuf:"bytes,7,opt,name=BannerImage,proto3" json:"BannerImage,omitempty"`
	AboutPatient                 string                 `protobuf:"bytes,8,opt,name=AboutPatient,proto3" json:"AboutPatient,omitempty"`
	TargetAmount                 int32                  `protobuf:"varint,9,opt,name=TargetAmount,proto3" json:"TargetAmount,omitempty"`
	ShowMedicalDocuments         bool                   `protobuf:"varint,10,opt,name=ShowMedicalDocuments,proto3" json:"ShowMedicalDocuments,omitempty"`
	ShowCollection               bool                   `protobuf:"varint,11,opt,name=ShowCollection,proto3" json:"ShowCollection,omitempty"`
	ShowDailyReport              bool                   `protobuf:"varint,12,opt,name=ShowDailyReport,proto3" json:"ShowDailyReport,omitempty"`
	ShowFundUpdates              bool                   `protobuf:"varint,13,opt,name=ShowFundUpdates,proto3" json:"ShowFundUpdates,omitempty"`
	CalculateCollection          int32                  `protobuf:"varint,14,opt,name=CalculateCollection,proto3" json:"CalculateCollection,omitempty"`
	TotalAmount                  float32                `protobuf:"fixed32,15,opt,name=TotalAmount,proto3" json:"TotalAmount,omitempty"`
	UpdatedAt                    *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
	UpdatedBy                    string                 `protobuf:"bytes,17,opt,name=UpdatedBy,proto3" json:"UpdatedBy,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *Settings) Reset() {
	*x = Settings{}
	mi := &file_proto_settings_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_proto_rawDescGZIP(), []int{0}
}

func (x *Settings) GetPatientName() string {
	if x != nil {
		return x.PatientName
	}
	return ""
}

func (x *Settings) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Settings) GetBannerTitle() string {
	if x != nil {
		return x.BannerTitle
	}
	return ""
}

func (x *Settings) GetHighlightedBannerTitle() string {
	if x != nil {
		return x.HighlightedBannerTitle
	}
	return ""
}

func (x *Settings) GetBannerDescription() string {
	if x != nil {
		return x.BannerDescription
	}
	return ""
}

func (x *Settings) GetHighlightedBannerDescription() string {
	if x != nil {
		return x.HighlightedBannerDescription
	}
	return ""
}

func (x *Settings) GetBannerImage() string {
	if x != nil {
		return x.BannerImage
	}
	return ""
}

func (x *Settings) GetAboutPatient() string {
	if x != nil {
		return x.AboutPatient
	}
	return ""
}

func (x *Settings) GetTargetAmount() int32 {
	if x != nil {
		return x.TargetAmount
	}
	return 0
}

func (x *Settings) GetShowMedicalDocuments() bool {
	if x != nil {
		return x.ShowMedicalDocuments
	}
	return false
}

func (x *Settings) GetShowCollection() bool {
	if x != nil {
		return x.ShowCollection
	}
	return false
}

func (x *Settings) GetShowDailyReport() bool {
	if x != nil {
		return x.ShowDailyReport
	}
	return false
}

func (x *Settings) GetShowFundUpdates() bool {
	if x != nil {
		return x.ShowFundUpdates
	}
	return false
}

func (x *Settings) GetCalculateCollection() int32 {
	if x != nil {
		return x.CalculateCollection
	}
	return 0
}

func (x *Settings) GetTotalAmount() float32 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Settings) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Settings) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

type GetSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sett          *Settings              `protobuf:"bytes,1,opt,name=Sett,proto3" json:"Sett,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsRequest) Reset() {
	*x = GetSettingsRequest{}
	mi := &file_proto_settings_settings_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsRequest) ProtoMessage() {}

func (x *GetSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsRequest.ProtoReflect.Descriptor instead.
func (*GetSettingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_proto_rawDescGZIP(), []int{1}
}

func (x *GetSettingsRequest) GetSett() *Settings {
	if x != nil {
		return x.Sett
	}
	return nil
}

type GetSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sett          *Settings              `protobuf:"bytes,1,opt,name=Sett,proto3" json:"Sett,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSettingsResponse) Reset() {
	*x = GetSettingsResponse{}
	mi := &file_proto_settings_settings_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSettingsResponse) ProtoMessage() {}

func (x *GetSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSettingsResponse.ProtoReflect.Descriptor instead.
func (*GetSettingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_proto_rawDescGZIP(), []int{2}
}

func (x *GetSettingsResponse) GetSett() *Settings {
	if x != nil {
		return x.Sett
	}
	return nil
}

type UpdateSettingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sett          *Settings              `protobuf:"bytes,1,opt,name=Sett,proto3" json:"Sett,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSettingsRequest) Reset() {
	*x = UpdateSettingsRequest{}
	mi := &file_proto_settings_settings_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSettingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSettingsRequest) ProtoMessage() {}

func (x *UpdateSettingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSettingsRequest.ProtoReflect.Descriptor instead.
func (*UpdateSettingsRequest) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSettingsRequest) GetSett() *Settings {
	if x != nil {
		return x.Sett
	}
	return nil
}

type UpdateSettingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sett          *Settings              `protobuf:"bytes,1,opt,name=Sett,proto3" json:"Sett,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSettingsResponse) Reset() {
	*x = UpdateSettingsResponse{}
	mi := &file_proto_settings_settings_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSettingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSettingsResponse) ProtoMessage() {}

func (x *UpdateSettingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSettingsResponse.ProtoReflect.Descriptor instead.
func (*UpdateSettingsResponse) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSettingsResponse) GetSett() *Settings {
	if x != nil {
		return x.Sett
	}
	return nil
}

var File_proto_settings_settings_proto protoreflect.FileDescriptor

const file_proto_settings_settings_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/settings/settings.proto\x12\bsettings\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x05\n" +
	"\bSettings\x12 \n" +
	"\vPatientName\x18\x01 \x01(\tR\vPatientName\x12\x14\n" +
	"\x05Title\x18\x02 \x01(\tR\x05Title\x12 \n" +
	"\vBannerTitle\x18\x03 \x01(\tR\vBannerTitle\x126\n" +
	"\x16HighlightedBannerTitle\x18\x04 \x01(\tR\x16HighlightedBannerTitle\x12,\n" +
	"\x11BannerDescription\x18\x05 \x01(\tR\x11BannerDescription\x12B\n" +
	"\x1cHighlightedBannerDescription\x18\x06 \x01(\tR\x1cHighlightedBannerDescription\x12 \n" +
	"\vBannerImage\x18\a \x01(\tR\vBannerImage\x12\"\n" +
	"\fAboutPatient\x18\b \x01(\tR\fAboutPatient\x12\"\n" +
	"\fTargetAmount\x18\t \x01(\x05R\fTargetAmount\x122\n" +
	"\x14ShowMedicalDocuments\x18\n" +
	" \x01(\bR\x14ShowMedicalDocuments\x12&\n" +
	"\x0eShowCollection\x18\v \x01(\bR\x0eShowCollection\x12(\n" +
	"\x0fShowDailyReport\x18\f \x01(\bR\x0fShowDailyReport\x12(\n" +
	"\x0fShowFundUpdates\x18\r \x01(\bR\x0fShowFundUpdates\x120\n" +
	"\x13CalculateCollection\x18\x0e \x01(\x05R\x13CalculateCollection\x12 \n" +
	"\vTotalAmount\x18\x0f \x01(\x02R\vTotalAmount\x128\n" +
	"\tUpdatedAt\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tUpdatedAt\x12\x1c\n" +
	"\tUpdatedBy\x18\x11 \x01(\tR\tUpdatedBy\"<\n" +
	"\x12GetSettingsRequest\x12&\n" +
	"\x04Sett\x18\x01 \x01(\v2\x12.settings.SettingsR\x04Sett\"=\n" +
	"\x13GetSettingsResponse\x12&\n" +
	"\x04Sett\x18\x01 \x01(\v2\x12.settings.SettingsR\x04Sett\"?\n" +
	"\x15UpdateSettingsRequest\x12&\n" +
	"\x04Sett\x18\x01 \x01(\v2\x12.settings.SettingsR\x04Sett\"@\n" +
	"\x16UpdateSettingsResponse\x12&\n" +
	"\x04Sett\x18\x01 \x01(\v2\x12.settings.SettingsR\x04Sett2\xb6\x01\n" +
	"\x0fSettingsService\x12L\n" +
	"\vGetSettings\x12\x1c.settings.GetSettingsRequest\x1a\x1d.settings.GetSettingsResponse\"\x00\x12U\n" +
	"\x0eUpdateSettings\x12\x1f.settings.UpdateSettingsRequest\x1a .settings.UpdateSettingsResponse\"\x00B\x12Z\x10./proto/settingsb\x06proto3"

var (
	file_proto_settings_settings_proto_rawDescOnce sync.Once
	file_proto_settings_settings_proto_rawDescData []byte
)

func file_proto_settings_settings_proto_rawDescGZIP() []byte {
	file_proto_settings_settings_proto_rawDescOnce.Do(func() {
		file_proto_settings_settings_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_settings_settings_proto_rawDesc), len(file_proto_settings_settings_proto_rawDesc)))
	})
	return file_proto_settings_settings_proto_rawDescData
}

var file_proto_settings_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_settings_settings_proto_goTypes = []any{
	(*Settings)(nil),               // 0: settings.Settings
	(*GetSettingsRequest)(nil),     // 1: settings.GetSettingsRequest
	(*GetSettingsResponse)(nil),    // 2: settings.GetSettingsResponse
	(*UpdateSettingsRequest)(nil),  // 3: settings.UpdateSettingsRequest
	(*UpdateSettingsResponse)(nil), // 4: settings.UpdateSettingsResponse
	(*timestamppb.Timestamp)(nil),  // 5: google.protobuf.Timestamp
}
var file_proto_settings_settings_proto_depIdxs = []int32{
	5, // 0: settings.Settings.UpdatedAt:type_name -> google.protobuf.Timestamp
	0, // 1: settings.GetSettingsRequest.Sett:type_name -> settings.Settings
	0, // 2: settings.GetSettingsResponse.Sett:type_name -> settings.Settings
	0, // 3: settings.UpdateSettingsRequest.Sett:type_name -> settings.Settings
	0, // 4: settings.UpdateSettingsResponse.Sett:type_name -> settings.Settings
	1, // 5: settings.SettingsService.GetSettings:input_type -> settings.GetSettingsRequest
	3, // 6: settings.SettingsService.UpdateSettings:input_type -> settings.UpdateSettingsRequest
	2, // 7: settings.SettingsService.GetSettings:output_type -> settings.GetSettingsResponse
	4, // 8: settings.SettingsService.UpdateSettings:output_type -> settings.UpdateSettingsResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_settings_settings_proto_init() }
func file_proto_settings_settings_proto_init() {
	if File_proto_settings_settings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_settings_settings_proto_rawDesc), len(file_proto_settings_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_settings_settings_proto_goTypes,
		DependencyIndexes: file_proto_settings_settings_proto_depIdxs,
		MessageInfos:      file_proto_settings_settings_proto_msgTypes,
	}.Build()
	File_proto_settings_settings_proto = out.File
	file_proto_settings_settings_proto_goTypes = nil
	file_proto_settings_settings_proto_depIdxs = nil
}
